// Replays the Rust-generated golden vectors (crates/kob-x402/vectors/golden/x402-payments.json, regenerated by
// `KOB_REGEN=1 cargo test -p kob-wasm --test x402_golden`) through the wasm build: payments for KAS, KCC-20 and
// swap-and-pay (local and wallet flow), preflight, revoke, requirement builders, hashes and digests. Objects are
// compared canonically (key order is not part of the wire); the signed transaction text and the
// PAYMENT-SIGNATURE header are compared byte for byte. The TS side (canonical JSON, offers, headers, request hash)
// must agree with Rust on the same inputs.

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { canonicalJson, httpRequestHash, requirementsHash, sha256Hex } from '../src/canonical.ts';
import { encodePaymentSignature } from '../src/headers.ts';
import { buildOffer } from '../src/offers.ts';
import type { OfferSpec } from '../src/types.ts';
import { loadGolden, realWasm, skipUnlessWasm } from './helpers/real-wasm.ts';

const opts = { skip: skipUnlessWasm };
const j = JSON.stringify;

/** How each golden `function` maps to the raw binding call. */
const ARGS: Record<string, (r: any) => string[]> = {
  x402NativeRequirements: (r) => [j(r)],
  x402Kcc20Requirements: (r) => [j(r)],
  x402TokenOffer: (r) => [j(r)],
  x402SwapRequirements: (r) => [j(r)],
  x402RequirementsHash: (r) => [j(r.requirements)],
  x402RequestHash: (r) => [r.method, r.url, r.body, r.requirementsHash],
  x402AddressToSpk: (r) => [r.address],
  x402SignedAuthDigest: (r) => [j(r.request)],
  x402PayloadCommitDigest: (r) => [j(r.request)],
  x402PayNative: (r) => [j(r)],
  x402PayKcc20: (r) => [j(r)],
  x402PaySwap: (r) => [j(r)],
  x402BuildKcc20Unsigned: (r) => [j(r)],
  x402FinishKcc20: (r) => [j(r.built), j(r.template), j(r.signatures)],
  x402PrepareSwap: (r) => [j(r)],
  x402FinishSwap: (r) => [j(r.prepared), j(r.signatures)],
  x402Preflight: (r) => [j(r)],
  x402Revoke: (r) => [j(r)],
};

test('every golden vector reproduces through the wasm', opts, () => {
  const kob = realWasm()!.raw as unknown as Record<string, (...a: string[]) => string>;
  const cases = loadGolden();
  assert.ok(cases.length >= 25);
  const seen = new Set<string>();
  for (const c of cases) {
    const args = ARGS[c.function];
    assert.ok(args, `${c.name}: unmapped function ${c.function}`);
    seen.add(c.function);
    const out = kob[c.function]!(...args(c.request));
    if (typeof c.expected === 'string') {
      assert.equal(out, c.expected, c.name);
    } else {
      const got = JSON.parse(out) as { paymentPayload?: { payload: { transaction: string } } };
      assert.equal(canonicalJson(got), canonicalJson(c.expected), c.name);
      if (got.paymentPayload) {
        assert.equal(got.paymentPayload.payload.transaction, c.expected.paymentPayload.payload.transaction, `${c.name}: transaction text`);
        if (c.signatureHeader) assert.equal(encodePaymentSignature(got.paymentPayload as never), c.signatureHeader, `${c.name}: PAYMENT-SIGNATURE`);
      }
    }
  }
  for (const f of Object.keys(ARGS)) assert.ok(seen.has(f), `no golden vector for ${f}`);
});

test('the wallet flow assembles exactly the payload of the local-key flow', () => {
  const cases = loadGolden();
  const by = (n: string) => cases.find((c) => c.name === n)!;
  assert.equal(by('wallet.kcc20.finish').expected.paymentPayload.payload.transaction, by('pay.kcc20').expected.paymentPayload.payload.transaction);
  assert.equal(by('wallet.swap.finish').expected.paymentPayload.payload.transaction, by('pay.swap.sw1').expected.paymentPayload.payload.transaction);
  // ... also when the pay asset is a KRON token: only the payer KAS input signs (address presence authorises the token)
  assert.equal(by('wallet.swap.kron.finish').expected.paymentPayload.payload.transaction, by('pay.swap.kron.sw1').expected.paymentPayload.payload.transaction);
  assert.equal(by('wallet.swap.kron.prepare').expected.built.sign.length, 1);
  // the wallet only ever sees sign requests and returns signatures
  assert.ok(by('wallet.kcc20.unsigned').expected.built.sign.length >= 1);
  assert.deepEqual(Object.keys(by('wallet.kcc20.finish').request.signatures[0]).sort(), ['inputIndex', 'signature']);
});

test('TS hashing and headers agree with Rust on the golden inputs', () => {
  const cases = loadGolden();
  for (const c of cases) {
    if (c.function === 'x402RequirementsHash') assert.equal(requirementsHash(c.request.requirements), c.expected, c.name);
    if (c.function === 'x402RequestHash') {
      assert.equal(httpRequestHash(c.request.method, c.request.url, JSON.parse(c.request.body), c.request.requirementsHash), c.expected, c.name);
    }
    if (c.function === 'x402SignedAuthDigest') {
      assert.equal(sha256Hex(canonicalJson({ scope: 'kaspa-x402-exact-request-authorization-v1', challengeId: null, ...c.request.request })), c.expected, c.name);
    }
    if (c.function === 'x402PayloadCommitDigest') {
      const r = c.request.request;
      const obj = {
        scope: 'kob-x402-payload-commitment-v1',
        network: r.network,
        profile: r.profile,
        route: r.routePayAsset ? { binding: 'kob-swap-v1', payAsset: r.routePayAsset } : null,
        asset: r.asset,
        amount: r.amount,
        payTo: r.payTo,
        payToScriptPublicKey: r.payToScriptPublicKey,
        paymentOutputIndex: r.paymentOutputIndex,
        paymentRequirementsHash: r.paymentRequirementsHash,
        requestHash: r.requestHash,
        expiresAt: r.expiresAt,
      };
      assert.equal(sha256Hex(canonicalJson(obj)), c.expected, c.name);
    }
    if (c.signatureHeader) assert.equal(encodePaymentSignature(c.expected.paymentPayload), c.signatureHeader, c.name);
  }
});

test('the TS offer builders produce the same entries as the Rust requirement builders', opts, () => {
  const wasm = realWasm()!;
  const cases = loadGolden();
  const by = (n: string) => cases.find((c) => c.name === n)!;
  const ctx = (o: { payTo: string; maxTimeoutSeconds: number }) => ({
    wasm,
    network: 'kaspa:testnet-10' as const,
    payTo: o.payTo,
    maxTimeoutSeconds: o.maxTimeoutSeconds,
    finality: 'accepted' as const,
  });

  const native = by('offer.native');
  assert.equal(canonicalJson(buildOffer({ kind: 'native', amount: native.request.amount }, ctx(native.request))), canonicalJson(native.expected));

  const kcc = by('offer.kcc20').request;
  const kccSpec: OfferSpec = {
    kind: 'kcc20',
    asset: kcc.asset,
    amount: kcc.amount,
    token: { custody: 'unconditional', carrier: kcc.carrier, templateHash: kcc.templateHash, extensionCommitment: kcc.extensionCommitment, ticker: kcc.ticker, decimals: kcc.decimals },
  };
  assert.equal(canonicalJson(buildOffer(kccSpec, ctx(kcc))), canonicalJson(by('offer.kcc20').expected));
  assert.equal(canonicalJson(wasm.tokenOffer({ ...kcc, custody: 'unconditional' })), canonicalJson(by('offer.kcc20.token').expected));

  const sk = by('offer.swap.kas').request;
  const pinned = (t: any) => ({ asset: t.covenantId, templateHash: t.templateHash, extensionCommitment: t.extensionCommitment });
  const skSpec: OfferSpec = { kind: 'swap', receive: 'kas', amount: sk.amount, payAssets: sk.payAssets.map(pinned) };
  assert.equal(canonicalJson(buildOffer(skSpec, ctx(sk))), canonicalJson(by('offer.swap.kas').expected));

  const st = by('offer.swap.token').request;
  const stSpec: OfferSpec = {
    kind: 'swap',
    receive: 'kcc20',
    amount: st.amount,
    asset: st.token.covenantId,
    token: { custody: 'unconditional', carrier: st.carrier, templateHash: st.token.templateHash, extensionCommitment: st.token.extensionCommitment, ticker: st.token.ticker, decimals: st.token.decimals },
    payAssets: st.payAssets.map(pinned),
  };
  assert.equal(canonicalJson(buildOffer(stSpec, ctx(st))), canonicalJson(by('offer.swap.token').expected));

  // the same route also accepting KAS as the pay asset
  const sk2 = by('offer.swap.token.kas').request;
  const kasSpec: OfferSpec = { ...stSpec, payAssets: sk2.payAssets.map((t: any) => (t.covenantId === 'KAS' ? { asset: 'KAS' } : pinned(t))) } as OfferSpec;
  assert.equal(canonicalJson(buildOffer(kasSpec, ctx(sk2))), canonicalJson(by('offer.swap.token.kas').expected));

  // a KRON pay asset (no extension commitment: the TS builder zero-fills it like the Rust builder), the same route paying a
  // KCC-20 merchant token, and a KaspaCom-template merchant token
  const kronPin = (t: any) => ({ asset: t.covenantId, templateHash: t.templateHash, ...(t.extensionCommitment ? { extensionCommitment: t.extensionCommitment } : { family: 'kron' as const }) });
  const k1 = by('offer.swap.kas.kron').request;
  const k1Spec: OfferSpec = { kind: 'swap', receive: 'kas', amount: k1.amount, payAssets: k1.payAssets.map(kronPin) };
  const k1Offer = buildOffer(k1Spec, ctx(k1));
  assert.equal(canonicalJson(k1Offer), canonicalJson(by('offer.swap.kas.kron').expected));
  assert.equal(k1Offer.extra.route?.payAssets[0]?.extensionCommitment, '0'.repeat(64));
  for (const name of ['offer.swap.token.kron', 'offer.swap.token.kaspacom']) {
    const r = by(name).request;
    const spec: OfferSpec = {
      kind: 'swap',
      receive: 'kcc20',
      amount: r.amount,
      asset: r.token.covenantId,
      // the KaspaCom program has issuer capabilities in the registry: the custody class is the program's
      token: { custody: r.token.custody, carrier: r.carrier, templateHash: r.token.templateHash, extensionCommitment: r.token.extensionCommitment, ticker: r.token.ticker, decimals: r.token.decimals },
      payAssets: r.payAssets.map(kronPin),
    };
    assert.equal(canonicalJson(buildOffer(spec, ctx(r))), canonicalJson(by(name).expected), name);
  }
  // a KaspaCom-template (mint / burn / freeze capable) token cannot be labelled unconditional
  assert.equal(by('offer.swap.token.kaspacom').expected.extra.token.custody, 'issuer-controlled');
  assert.throws(() => wasm.tokenOffer({ ...kcc, templateHash: by('offer.swap.token.kaspacom').request.token.templateHash, custody: 'unconditional' }), /cannot be labelled unconditional/);
  // a KRON token cannot be the merchant kcc20 asset
  assert.throws(() => wasm.tokenOffer({ ...kcc, asset: '72'.repeat(32), templateHash: k1.payAssets[0].templateHash, extensionCommitment: '00'.repeat(32), custody: 'unconditional' }));
});

test('rejections carry the verifier diagnostic', opts, () => {
  const wasm = realWasm()!;
  const pre = loadGolden().find((c) => c.name === 'preflight.native')!.request;
  const base = { requirements: pre.offer, paymentPayload: pre.payload, requestHash: pre.requestHash, nowMs: Number(pre.nowMs) };
  assert.equal(wasm.preflight(base).ok, true);
  const expired = wasm.preflight({ ...base, nowMs: base.nowMs + 3_600_000 });
  assert.equal(expired.ok, false);
  assert.equal(expired.diagnostic, 'expired_authorization');
  const tampered = structuredClone(pre.payload);
  tampered.accepted.amount = '1';
  assert.equal(wasm.preflight({ ...base, paymentPayload: tampered }).ok, false);
  assert.equal(wasm.preflight({ ...base, requestHash: 'b2'.repeat(32) }).ok, false);
});

test('a payer signature with a hash type other than SIGHASH_ALL is refused: by the verifier, and by the wallet-signature intake', opts, () => {
  const cases = loadGolden();
  const by = (n: string) => cases.find((c) => c.name === n)!;
  // the Rust verifier (through the wasm) refuses a correctly signed NONE / SINGLE / ANYONECANPAY payment
  const negatives = cases.filter((c) => c.name.startsWith('preflight.kcc20.hashtype.'));
  assert.deepEqual(negatives.map((c) => c.name.slice(-4)).sort(), ['0x02', '0x04', '0x81', '0x82', '0x84']);
  for (const c of negatives) {
    assert.equal(c.expected.ok, false, c.name);
    assert.equal(c.expected.diagnostic, 'token_owner_scheme', c.name);
  }
  // a wallet that answers with a non-ALL signature never gets a payment assembled from it
  const kob = realWasm()!.raw as unknown as Record<string, (...a: string[]) => string>;
  const fin = by('wallet.kcc20.finish').request;
  const sigs = fin.signatures.map((s: { inputIndex: number; signature: string }) => ({ ...s }));
  assert.ok(sigs[0].signature.endsWith('01'), 'the golden wallet signature is a 65-byte SIGHASH_ALL signature');
  for (const t of ['02', '04', '81', '82', '84']) {
    const bad = sigs.map((s: { inputIndex: number; signature: string }, i: number) => (i === 0 ? { ...s, signature: s.signature.slice(0, -2) + t } : s));
    assert.throws(() => kob.x402FinishKcc20!(j(fin.built), j(fin.template), j(bad)), /SIGHASH_ALL/, `hash type 0x${t}`);
  }
});
