//! The size of a 1:1 Argent port of a hand-written order (docs/argent-feedback.md, item 10).
//!
//! `contracts/argent/port/kob_ask_port.ag` is `contracts/v2/KobAsk.sil` ported 1:1 to Argent (the body verbatim, plus
//! the `emits next: KobAsk[0..=1]` / `become` Argent requires); `scripts/build-argent.sh` publishes its generated
//! SilverScript under `contracts/argent/port-out/`. This test compiles the hand-written order and the port with the same
//! constructor arguments and attributes the difference in bytes: each generated check and each body check it duplicates
//! is removed from the source on its own and the compiled size is measured again. Run with `--nocapture` for the table.

mod common;

use silverscript_abi::ArtifactValue;
use silverscript_lang::compiler::CompileOptions;

use common::{bytecode, compile_contract, repo_root};

fn read(rel: &str) -> String {
    std::fs::read_to_string(repo_root().join(rel)).unwrap_or_else(|e| panic!("{rel}: {e}")).replace("\r\n", "\n")
}

fn size(src: &str, what: &str) -> usize {
    let ctor: Vec<ArtifactValue> = serde_json::from_str(&read("contracts/v2/KobAsk.ctor.json")).expect("ctor json");
    bytecode(&compile_contract(src, &ctor, CompileOptions::default()).unwrap_or_else(|e| panic!("compile {what}: {e:?}"))).len()
}

/// `src` with every `(needle, replacement)` applied; each needle must occur exactly `n` times.
fn edit(src: &str, edits: &[(&str, &str, usize)]) -> String {
    let mut s = src.to_string();
    for (needle, with, n) in edits {
        assert_eq!(s.matches(needle).count(), *n, "the source changed: `{needle}` must occur {n} time(s)");
        s = s.replace(needle, with);
    }
    s
}

// Generated by argentc for `emits next: KobAsk[0..=1]` / `become next <- KobAsk[](cont)`.
const GEN_BOUNDS: (&str, &str, usize) =
    ("        require(gen__next_output_count >= 0);\n        require(gen__next_output_count <= 1);\n", "", 1);
const GEN_BECOME: (&str, &str, usize) = (
    "        require(cont.length == gen__next_output_count);\n        for (gen__next_output_position, 0, gen__next_output_count, 1) {\n            State gen__source_next_kob_ask_state = cont[gen__next_output_position];\n            // :: become KobAsk\n            validateOutputState(\n                OpAuthOutputIdx(this.activeInputIndex, gen__next_output_position),\n                gen__source_next_kob_ask_state\n            );\n        }\n",
    "",
    1,
);
// Generated for `cancel ... emits none`.
const GEN_CANCEL: (&str, &str, usize) = ("        require(OpAuthOutputCount(this.activeInputIndex) == 0);\n\n", "", 1);
// The continuation state the port builds for `become` (the hand-written order splices amountLeft into its own script).
const PORT_CONT: [(&str, &str, usize); 2] = [
    ("        State[] cont;\n", "", 1),
    (
        "                cont = cont.append(State {\n                    // :: user declared fields\n                    maker: maker,\n                    tokenCovId: tokenCovId,\n                    tokenTplHash: tokenTplHash,\n                    tplPrefixLen: tplPrefixLen,\n                    tplSuffixLen: tplSuffixLen,\n                    scale: scale,\n                    minFill: minFill,\n                    price: price,\n                    tip: tip,\n                    tif: tif,\n                    activeFrom: activeFrom,\n                    expiryDaa: expiryDaa,\n                    refundTip: refundTip,\n                    interval: interval,\n                    maxFill: maxFill,\n                    slope: slope,\n                    priceEnd: priceEnd,\n                    decayStep: decayStep,\n                    amountLeft: amountLeft - n,\n                    extensionCommitment: extensionCommitment,\n                });\n",
        "",
        1,
    ),
];
// Body checks of the original that the generated ones repeat.
const BODY_COUNT: [(&str, &str, usize); 2] =
    [("require(OpCovOutputCount(selfId) == 1);", "", 1), ("require(OpCovOutputCount(selfId) == 0);", "", 2)];
const BODY_SPK: (&str, &str, usize) =
    ("                require(tx.outputs[selfOut].scriptPubKey == contSpk(amountLeft - n));\n", "", 1);

#[test]
fn kob_ask_port_size_attribution() {
    let hand = read("contracts/v2/KobAsk.sil");
    let port = read("contracts/argent/port-out/KobAsk.port.sil");
    let h = size(&hand, "hand-written KobAsk");
    let p = size(&port, "port");
    let without = |edits: &[(&str, &str, usize)], what: &str| size(&edit(&port, edits), what);

    let g_bounds = p - without(&[GEN_BOUNDS], "port - generated count bounds");
    let g_become = p - without(&[GEN_BECOME], "port - generated become");
    let g_cancel = p - without(&[GEN_CANCEL], "port - generated cancel check");
    let no_become = without(&[GEN_BECOME], "port - become");
    let c_cont = no_become - size(&edit(&port, &[GEN_BECOME, PORT_CONT[0], PORT_CONT[1]]), "port - become - cont");
    let d_count = p - without(&BODY_COUNT, "port - body output counts");
    let d_spk = p - without(&[BODY_SPK], "port - body continuation SPK");
    let dedup = without(&[BODY_COUNT[0], BODY_COUNT[1], BODY_SPK], "port - duplicated body checks");
    let skeleton = size(&edit(&port, &[GEN_BOUNDS, GEN_BECOME, GEN_CANCEL, PORT_CONT[0], PORT_CONT[1]]), "port - Argent additions");

    println!("KobAsk, hand-written (contracts/v2/KobAsk.sil)                {h:>5} B");
    println!("KobAsk, 1:1 Argent port (contracts/argent/port-out)           {p:>5} B  ({:+} vs hand-written)", p as i64 - h as i64);
    println!("  generated: output count bounds (0 <= count <= 1)            {g_bounds:>5} B");
    println!("  generated: become (count == len, validateOutputState)       {g_become:>5} B");
    println!("  generated: cancel `OpAuthOutputCount == 0`                  {g_cancel:>5} B");
    println!("  port: the continuation state literal for `become`           {c_cont:>5} B");
    println!(
        "  port without all of the above                               {skeleton:>5} B  ({:+} vs hand-written)",
        skeleton as i64 - h as i64
    );
    println!("  body checks the generated ones repeat:");
    println!("    OpCovOutputCount(selfId) == 1 / == 0 (x2)                 {d_count:>5} B");
    println!("    continuation SPK == contSpk(amountLeft - n)                 {d_spk:>5} B");
    println!(
        "  port without the repeated body checks                       {dedup:>5} B  ({:+} vs hand-written)",
        dedup as i64 - h as i64
    );

    assert!(p > h, "the port is larger than the hand-written order");
    assert!(g_become > 0 && g_bounds > 0 && g_cancel > 0 && d_count > 0 && d_spk > 0);
}
