//! KCC-20 per-transaction slot limits: the reference token (argent kcc20-reference c8a0871) at its
//! default 3 inputs / 3 outputs and the KOB variants 4x5, 8x8 and 16x16
//! (`contracts/kcc20/variants/`, generated by `kob_protocol::kcc20::kcc20_source_with_limits`).
//!
//! For every variant this measures the program size, the static sig-op upper bound and real
//! transfers in rusty-kaspa v2.1.0's TxScriptEngine (covenant context, script-unit metering):
//! per-input script units and compute budget, tx bytes, compute mass, storage mass and the
//! minimum relay fee. Negative cases: one input or output above the limit, and a conservation
//! break, are rejected by the leader.
//!
//! Run: cargo test --release -p kob-tests --test kcc20_limits_tests -- --nocapture --test-threads=1

mod common;

use std::collections::BTreeMap;

use kaspa_consensus_core::hashing::sighash::{calc_schnorr_signature_hash, SigHashReusedValuesUnsync};
use kaspa_consensus_core::hashing::sighash_type::SigHashType;
use kaspa_consensus_core::mass::{transaction_estimated_serialized_size, MassCalculator};
use kaspa_consensus_core::tx::{
    CovenantBinding, MutableTransaction, PopulatedTransaction, ScriptPublicKey, Transaction, TransactionId, TransactionInput,
    TransactionOutpoint, TransactionOutput, UtxoEntry,
};
use kaspa_consensus_core::Hash;
use kaspa_txscript::caches::Cache;
use kaspa_txscript::covenants::CovenantsContext;
use kaspa_txscript::opcodes::codes::OpTrue;
use kaspa_txscript::{pay_to_script_hash_script, EngineCtx, EngineFlags, TxScriptEngine};
use kaspa_txscript_errors::TxScriptError;
use rand::{thread_rng, RngCore};
use secp256k1::{Keypair, Secp256k1, SecretKey};
use silverscript_abi::{ArtifactValue, SilAbiArtifact};
use silverscript_lang::compiler::CompileOptions;

use common::{bytecode, compile_contract, compiled_template_parts_and_hash, encode_entry_sig_script, push_redeem_script};

const KAS: i64 = 100_000_000;
const TOKEN_COV: Hash = Hash::from_bytes([0x70; 32]);
const OWNER_COV: Hash = Hash::from_bytes([0xc0; 32]);
const EXT: [u8; 32] = [0xee; 32];
const SCHEME_P2PK: u8 = 0x00;
const SCHEME_COVID: u8 = 0x04;
const SIGOP_SCRIPT_UNITS: u64 = 100_000;
const FREE_UNITS: u64 = 9_999;
const UNITS_PER_BUDGET: u64 = 10_000;
const MIN_FEE_PER_GRAM: u64 = 100;
const CARRIER: i64 = 10 * KAS;

/// (source name, max token inputs, max token outputs)
const VARIANTS: [(&str, usize, usize); 4] =
    [("KCC20Ref", 3, 3), ("KCC20Ref_4x5", 4, 5), ("KCC20Ref_8x8", 8, 8), ("KCC20Ref_16x16", 16, 16)];

fn keypair() -> Keypair {
    let secp = Secp256k1::new();
    let mut rng = thread_rng();
    let mut sk = [0u8; 32];
    loop {
        rng.fill_bytes(&mut sk);
        if let Ok(s) = SecretKey::from_slice(&sk) {
            return Keypair::from_secret_key(&secp, &s);
        }
    }
}
fn pk(kp: &Keypair) -> [u8; 32] {
    kp.x_only_public_key().0.serialize()
}

struct Token {
    name: &'static str,
    art: SilAbiArtifact,
    prefix: Vec<u8>,
    suffix: Vec<u8>,
}

fn tok_state_bytes(amount: i64, owner: &[u8; 32], scheme: u8) -> Vec<u8> {
    let mut v = vec![0x08];
    v.extend_from_slice(&amount.to_le_bytes());
    v.push(0x20);
    v.extend_from_slice(owner);
    v.extend_from_slice(&[0x01, scheme, 0x01, 0x00, 0x20]);
    v.extend_from_slice(&[0u8; 32]);
    v.push(0x20);
    v.extend_from_slice(&EXT);
    v
}
impl Token {
    fn new(name: &'static str) -> Self {
        let art = compile_contract(
            &common::contract_source(name),
            &[
                ArtifactValue::Int(1000),
                vec![3u8; 32].into(),
                ArtifactValue::Byte(SCHEME_COVID),
                ArtifactValue::Byte(0),
                vec![0u8; 32].into(),
                EXT.to_vec().into(),
            ],
            CompileOptions::default(),
        )
        .unwrap_or_else(|e| panic!("compile {name}: {e}"));
        let (prefix, suffix, _hash) = compiled_template_parts_and_hash(&art);
        let t = Token { name, art, prefix, suffix };
        assert_eq!(t.redeem(1000, &[3u8; 32], SCHEME_COVID), bytecode(&t.art), "manual KCC-20 state encoding must match compiler");
        t
    }
    fn redeem(&self, amount: i64, owner: &[u8; 32], scheme: u8) -> Vec<u8> {
        [self.prefix.clone(), tok_state_bytes(amount, owner, scheme), self.suffix.clone()].concat()
    }
    fn spk(&self, amount: i64, owner: &[u8; 32], scheme: u8) -> ScriptPublicKey {
        pay_to_script_hash_script(&self.redeem(amount, owner, scheme))
    }
}
fn tok_state(amount: i64, owner: &[u8; 32], scheme: u8) -> ArtifactValue {
    BTreeMap::from([
        ("amount".to_string(), ArtifactValue::Int(amount)),
        ("owner".to_string(), owner.to_vec().into()),
        ("owner_scheme".to_string(), ArtifactValue::Byte(scheme)),
        ("borrow_scheme".to_string(), ArtifactValue::Byte(0)),
        ("borrow_guard".to_string(), vec![0u8; 32].into()),
        ("extension_commitment".to_string(), EXT.to_vec().into()),
    ])
    .into()
}

#[derive(Clone)]
enum Owner {
    P2pk(Keypair),
    Cov,
}
impl Owner {
    fn key(&self) -> ([u8; 32], u8) {
        match self {
            Owner::P2pk(kp) => (pk(kp), SCHEME_P2PK),
            Owner::Cov => (OWNER_COV.as_bytes(), SCHEME_COVID),
        }
    }
}
#[derive(Clone)]
enum Role {
    Leader { redeem: Vec<u8>, next: Vec<ArtifactValue>, owner: Owner },
    Delegate { redeem: Vec<u8>, owner: Owner },
    OwnerCov,
}
#[derive(Clone)]
struct Inp {
    entry: UtxoEntry,
    role: Role,
}
struct Scn {
    name: String,
    inputs: Vec<Inp>,
    outputs: Vec<TransactionOutput>,
}

fn role_name(r: &Role) -> &'static str {
    match r {
        Role::Leader { .. } => "kcc20.transfer",
        Role::Delegate { .. } => "kcc20.delegator",
        Role::OwnerCov => "owner-cov(OpTrue)",
    }
}

/// k_in token inputs (all owned by `owners[i]`) -> k_out token outputs; amounts 1000 per input,
/// output split evenly (remainder on output 0). `extra_amount` breaks conservation when != 0.
fn transfer(t: &Token, k_in: usize, k_out: usize, owners: &[Owner], extra_amount: i64) -> Scn {
    let total = 1000 * k_in as i64;
    let recv: Vec<[u8; 32]> = (0..k_out).map(|j| [0x40 + j as u8; 32]).collect();
    let mut amounts: Vec<i64> = vec![total / k_out as i64; k_out];
    amounts[0] += total - amounts.iter().sum::<i64>() + extra_amount;
    let next: Vec<ArtifactValue> = (0..k_out).map(|j| tok_state(amounts[j], &recv[j], SCHEME_P2PK)).collect();
    let mut inputs = vec![];
    for i in 0..k_in {
        let owner = owners[i % owners.len()].clone();
        let (o, s) = owner.key();
        let redeem = t.redeem(1000, &o, s);
        let entry = UtxoEntry::new(CARRIER as u64, pay_to_script_hash_script(&redeem), 0, false, Some(TOKEN_COV));
        let role = if i == 0 { Role::Leader { redeem, next: next.clone(), owner } } else { Role::Delegate { redeem, owner } };
        inputs.push(Inp { entry, role });
    }
    if owners.iter().any(|o| matches!(o, Owner::Cov)) {
        let spk = ScriptPublicKey::new(0, vec![OpTrue].into());
        inputs.push(Inp { entry: UtxoEntry::new(CARRIER as u64, spk, 0, false, Some(OWNER_COV)), role: Role::OwnerCov });
    }
    let in_value = CARRIER * inputs.len() as i64;
    let out_value = (in_value - KAS) / k_out as i64; // 1 KAS left for the fee
    let outputs = (0..k_out)
        .map(|j| TransactionOutput {
            value: out_value as u64,
            script_public_key: t.spk(amounts[j], &recv[j], SCHEME_P2PK),
            covenant: Some(CovenantBinding { authorizing_input: 0, covenant_id: TOKEN_COV }),
        })
        .collect();
    let kind = if matches!(owners[0], Owner::Cov) { "covid owners" } else { "p2pk owners" };
    Scn { name: format!("{} {k_in} in -> {k_out} out ({kind})", t.name), inputs, outputs }
}

fn sign(tx: &Transaction, entries: &[UtxoEntry], idx: usize, kp: &Keypair) -> Vec<u8> {
    let mt = MutableTransaction::with_entries(tx.clone(), entries.to_vec());
    let reused = SigHashReusedValuesUnsync::new();
    let h = calc_schnorr_signature_hash(&mt.as_verifiable(), idx, SigHashType::from_u8(1).unwrap(), &reused);
    let msg = secp256k1::Message::from_digest_slice(h.as_bytes().as_slice()).expect("msg");
    let mut s = kp.sign_schnorr(msg).as_ref().to_vec();
    s.push(1);
    s
}

fn build(t: &Token, s: &Scn, budgets: &[u16]) -> (Transaction, Vec<UtxoEntry>) {
    let entries: Vec<UtxoEntry> = s.inputs.iter().map(|i| i.entry.clone()).collect();
    let inputs: Vec<TransactionInput> = (0..s.inputs.len())
        .map(|k| {
            TransactionInput::new_with_compute_budget(
                TransactionOutpoint { transaction_id: TransactionId::from_bytes([k as u8 + 1; 32]), index: k as u32 },
                vec![],
                0,
                budgets.get(k).copied().unwrap_or(0),
            )
        })
        .collect();
    let mut tx = Transaction::new(1, inputs, s.outputs.clone(), 0, Default::default(), 0, vec![]);
    let unsigned = tx.clone();
    for (k, inp) in s.inputs.iter().enumerate() {
        let wit = |o: &Owner| match o {
            Owner::P2pk(kp) => sign(&unsigned, &entries, k, kp),
            Owner::Cov => vec![],
        };
        let ss = match &inp.role {
            Role::Leader { redeem, next, owner } => {
                let w = [vec![0x00], wit(owner)].concat();
                let mut ss = encode_entry_sig_script(&t.art, "transfer", &[ArtifactValue::Array(next.clone()), w.into()]).unwrap();
                ss.extend_from_slice(&push_redeem_script(redeem));
                ss
            }
            Role::Delegate { redeem, owner } => {
                let mut ss = encode_entry_sig_script(&t.art, "transfer_delegator", &[wit(owner).into()]).unwrap();
                ss.extend_from_slice(&push_redeem_script(redeem));
                ss
            }
            Role::OwnerCov => vec![],
        };
        tx.inputs[k].signature_script = ss;
    }
    (tx, entries)
}

fn execute(tx: &Transaction, entries: &[UtxoEntry]) -> Result<Vec<Result<u64, TxScriptError>>, String> {
    let populated = PopulatedTransaction::new(tx, entries.to_vec());
    let cov_ctx = CovenantsContext::from_tx(&populated).map_err(|e| format!("covenant context: {e:?}"))?;
    let reused = SigHashReusedValuesUnsync::new();
    let cache = Cache::new(10_000);
    Ok((0..tx.inputs.len())
        .map(|i| {
            let input = tx.inputs[i].clone();
            let mut vm = TxScriptEngine::from_transaction_input(
                &populated,
                &input,
                i,
                &entries[i],
                EngineCtx::new(&cache).with_reused(&reused).with_covenants_ctx(&cov_ctx),
                EngineFlags { sigop_script_units: SIGOP_SCRIPT_UNITS.into() },
            );
            vm.execute().map(|_| vm.used_script_units().0)
        })
        .collect())
}

fn run_ok(t: &Token, s: &Scn) {
    let (tx, entries) = build(t, s, &[]);
    let res = execute(&tx, &entries).unwrap_or_else(|e| panic!("{}: {e}", s.name));
    let mut budgets = vec![];
    for (i, r) in res.iter().enumerate() {
        match r {
            Ok(u) => budgets.push(u.saturating_sub(FREE_UNITS).div_ceil(UNITS_PER_BUDGET) as u16),
            Err(e) => panic!("{}: input {i} ({}) failed: {e:?}", s.name, role_name(&s.inputs[i].role)),
        }
    }
    let (tx, entries) = build(t, s, &budgets);
    let res = execute(&tx, &entries).expect("ctx");
    assert!(res.iter().all(|r| r.is_ok()), "{}: second pass failed", s.name);
    let mc = MassCalculator::new(1, 10, 1_000_000_000_000);
    let nc = mc.calc_non_contextual_masses(&tx);
    let populated = PopulatedTransaction::new(&tx, entries.clone());
    let storage = mc.calc_contextual_masses(&populated).map(|c| c.storage_mass).unwrap_or(u64::MAX);
    let size = transaction_estimated_serialized_size(&tx);
    let fee_mass = nc.compute_mass.max(2 * size).max(storage);
    let leader_units = res[0].as_ref().unwrap();
    let deleg: Vec<u64> = s
        .inputs
        .iter()
        .zip(res.iter())
        .filter(|(i, _)| matches!(i.role, Role::Delegate { .. }))
        .map(|(_, r)| *r.as_ref().unwrap())
        .collect();
    let deleg_str =
        if deleg.is_empty() { "-".to_string() } else { format!("{}..{}", deleg.iter().min().unwrap(), deleg.iter().max().unwrap()) };
    let sig_bytes: usize = tx.inputs.iter().map(|i| i.signature_script.len()).sum();
    println!(
        "ROW {} | leader_units={} budget={} | delegator_units={} | sigscript_total={} B | tx_size={} B | compute_mass={} | storage_mass={} | fee_mass={} | min_fee={} sompi ({:.5} KAS) | fee/token-input={:.5} KAS",
        s.name,
        leader_units,
        budgets[0],
        deleg_str,
        sig_bytes,
        size,
        nc.compute_mass,
        storage,
        fee_mass,
        fee_mass * MIN_FEE_PER_GRAM,
        (fee_mass * MIN_FEE_PER_GRAM) as f64 / 1e8,
        (fee_mass * MIN_FEE_PER_GRAM) as f64 / 1e8 / s.inputs.iter().filter(|i| !matches!(i.role, Role::OwnerCov)).count() as f64
    );
}

fn run_bad(t: &Token, s: &Scn, expect: usize) {
    let (tx, entries) = build(t, s, &[]);
    match execute(&tx, &entries) {
        Err(e) => println!("NEGATIVE {} [REJECTED at tx level: {e}]", s.name),
        Ok(res) => {
            let r = &res[expect];
            assert!(r.is_err(), "{}: expected input {expect} ({}) to REJECT but it passed", s.name, role_name(&s.inputs[expect].role));
            println!(
                "NEGATIVE {} [REJECTED at in[{expect}] {}: {:?}]",
                s.name,
                role_name(&s.inputs[expect].role),
                r.as_ref().unwrap_err()
            );
        }
    }
}

#[test]
fn kcc20_variant_sizes_and_sigops() {
    let base = Token::new("KCC20Ref");
    for (name, max_in, max_out) in VARIANTS {
        let t = Token::new(name);
        let bc = bytecode(&t.art);
        let so = kaspa_txscript::get_sig_op_count_upper_bound::<PopulatedTransaction, SigHashReusedValuesUnsync>(
            &push_redeem_script(&bc),
            &pay_to_script_hash_script(&bc),
        );
        println!(
            "SIZE {name} ({max_in} in / {max_out} out): redeem {} B (prefix {} + state 112 + suffix {}), +{} B vs 3x3, static sig-op upper bound {so}",
            bc.len(),
            t.prefix.len(),
            t.suffix.len(),
            bc.len() as i64 - bytecode(&base.art).len() as i64,
        );
        assert!(so <= 15, "{name}: static sig-op bound {so} exceeds the 15 standardness cap");
    }
}

#[test]
fn kcc20_variant_sources_match_generator() {
    let base = common::contract_source("KCC20Ref");
    for (name, max_in, max_out) in VARIANTS.iter().skip(1) {
        let generated = kob_protocol::kcc20::kcc20_source_with_limits(&base, *max_in, *max_out).expect("generate");
        common::check_generated_source(name, &generated);
    }
    assert_eq!(kob_protocol::kcc20::kcc20_source_with_limits(&base, 3, 3).unwrap(), base, "3x3 must be the reference itself");
}

#[test]
fn kcc20_variant_transfers() {
    let alice = keypair();
    for (name, max_in, max_out) in VARIANTS {
        let t = Token::new(name);
        let mut shapes: Vec<(usize, usize)> = vec![(1, 1), (3, 3), (max_in, max_out)];
        for k in [4usize, 8, 16] {
            if k <= max_in && k <= max_out {
                shapes.push((k, k));
            }
        }
        shapes.sort();
        shapes.dedup();
        for (ki, ko) in shapes {
            run_ok(&t, &transfer(&t, ki, ko, &[Owner::P2pk(alice)], 0));
            run_ok(&t, &transfer(&t, ki, ko, &[Owner::Cov], 0));
        }
        // negative: one input above the limit, one output above the limit, conservation break
        let mut s = transfer(&t, max_in + 1, 1, &[Owner::Cov], 0);
        s.name = format!("{name}: {} token inputs (limit {max_in})", max_in + 1);
        run_bad(&t, &s, 0);
        let mut s = transfer(&t, 1, max_out + 1, &[Owner::Cov], 0);
        s.name = format!("{name}: {} token outputs (limit {max_out})", max_out + 1);
        run_bad(&t, &s, 0);
        let mut s = transfer(&t, max_in, max_out, &[Owner::Cov], 1);
        s.name = format!("{name}: conservation break (+1 unit minted) at {max_in}x{max_out}");
        run_bad(&t, &s, 0);
    }
}
