// KRON buy-side suite: contracts/adapters/kron/v2 (KobCondBidKron, KobIfdAskKron), protocol v3 (no lots).
// Ported from the protocol v2 catalog: ids, notes and expectations preserved, every edit retargeted to the v3
// contract text (amounts in base units, prices sompi per whole token, quoteOf rounding, merge argument -(k * 2^53 + m)).
// New v3 checks get their own mutations (minFill, the quoteOf floor / ceil choices, price >= tip, the update parent
// guard; the 0x08 first-byte merge checks are defence in depth and HELD). IA24a / IA24b are defence in depth (two
// independent binds of the booked exit): removing either alone must NOT flip anything.
import { del, rep, rx, rxDel } from '../lib/edits.mjs';
import { touchMutations } from '../lib/touch.mjs';

export const suite = {
  name: 'kron-buy',
  family: 'KRON adapter (v3, buy-side contracts)',
  testBin: 'kob_kron_v2_buy_tests',
  srcDir: 'contracts/adapters/kron/v2',
  templateMarker: /^=== KRON template (\S+)/,
  expectedTemplates: 2,
};

const T_TRAIL = 'kron_v2_buy_trail_cap_attack';
const T_LIFE = 'kron_v2_buy_lifecycle';
const T_NEG = 'kron_v2_buy_negative';
const T_RPT = 'kron_v2_buy_repeat_ifd_attacks';
const T_DUST = 'kron_v2_buy_lifecycle_dust_custody';
// new v3 check batteries
const T_MINFILL = 'kron_v2_buy_v3_min_fill';
const T_ROUND = 'kron_v2_buy_v3_rounding';
const T_TIP = 'kron_v2_buy_v3_tip';
const T_MERGE = 'kron_v2_buy_v3_merge_push';
// touch trigger batteries, one test fn per trigger kind
const T_BS = 'kron_v2_buy_touch_cond_settle';
const T_BA = 'kron_v2_buy_touch_cond_arm';
const T_BT = 'kron_v2_buy_touch_cond_trail';
const T_AF = 'kron_v2_buy_touch_ifd_fill';
const T_AA = 'kron_v2_buy_touch_ifd_arm';

export const mutations = [
  // ---- KobCondBidKron
  {
    id: 'CB1',
    file: 'KobCondBidKron',
    test: T_LIFE,
    expect: ['NS10'],
    note: 'settle: noStrays(selfId) call',
    edits: [rxDel('entry settle(', /^\s*noStrays\(selfId\);\s*$/m)],
  },
  {
    id: 'CB1b',
    file: 'KobCondBidKron',
    test: T_NEG,
    expect: ['KB-P3b'],
    inputOnly: ['KB-P3b'], // the token program rejects the 5-token-input transaction on its own input; the order input is what flips
    note: 'noStrays: scan bound require(cnt <= MAX_TOK_IN) (the scan is unrolled over MAX_TOK_IN slots: a further input is not scanned)',
    edits: [rxDel('function noStrays', /^\s*require\(cnt <= MAX_TOK_IN\);\s*$/m)],
  },
  {
    id: 'CB2',
    file: 'KobCondBidKron',
    test: T_LIFE,
    expect: ['NS11'],
    note: 'refund: require(OpCovInputCount(tokenCovId) == 0)',
    edits: [rxDel('entry refund()', /^\s*require\(OpCovInputCount\(tokenCovId\) == 0\);.*$/m)],
  },
  {
    id: 'CB3',
    file: 'KobCondBidKron',
    run: { [T_LIFE]: ['NS12'], [T_BA]: ['NTV23'], [T_BT]: ['NTW23'] },
    note: 'update refuses token inputs owned by the order (touch: the evidence fill brings foreign token inputs)',
    edits: [rxDel('entry update(', /^\s*noStrays\(selfId\);$/m)],
  },
  {
    id: 'CB4',
    file: 'KobCondBidKron',
    test: T_LIFE,
    expect: ['NB29'],
    note: 'stop auction: require(t >= newArmed) (origin bound)',
    edits: [rxDel('entry settle(', /^\s*require\(t >= newArmed\);\s*$/m)],
  },
  {
    id: 'CB5',
    file: 'KobCondBidKron',
    run: { [T_LIFE]: ['NB27'], [T_NEG]: ['NB1', 'NB4'] },
    note: 'settle: continuation value >= keep',
    edits: [rxDel('entry settle(', /^\s*require\(tx\.outputs\[selfOut\]\.value >= keep\);\s*$/m)],
  },
  {
    id: 'CB6',
    file: 'KobCondBidKron',
    run: { [T_LIFE]: ['NB28'], [T_NEG]: ['NB15', 'NB16'] },
    note: 'settle: continuation script == contSpk (auction origin carried, no restart)',
    edits: [
      rxDel('entry settle(', /^\s*require\(tx\.outputs\[selfOut\]\.scriptPubKey == contSpk\(stopPrice, amountLeft - n, newArmed\)\);\s*$/m),
    ],
  },
  {
    id: 'CB7',
    file: 'KobCondBidKron',
    run: { [T_LIFE]: ['NB30'], [T_NEG]: ['NB25'] },
    note: 'update: keeper takes at most keeperTip (value >= in - keeperTip)',
    edits: [
      rx('entry update(', /tx\.outputs\[selfOut\]\.value >= tx\.inputs\[self\]\.value - keeperTip/, 'tx.outputs[selfOut].value >= 0'),
    ],
  },
  {
    id: 'CB8',
    file: 'KobCondBidKron',
    test: T_TRAIL,
    expect: ['NB22b'],
    note: 'trail: cap step count below the limit leg (k = min(k, kf))',
    edits: [rxDel('entry update(', /^\s*if \(kf < k\) \{ k = kf; \}\s*$/m)],
  },
  {
    id: 'CB9',
    file: 'KobCondBidKron',
    test: T_RPT,
    expect: ['NRPB13'],
    note: 'repeat: stop-leg fill refuses the entry (require(present == 0))',
    edits: [rxDel('entry settle(', /^\s*require\(present == 0\);\s*$/m)],
  },
  {
    id: 'CB10',
    file: 'KobCondBidKron',
    test: T_RPT,
    expect: ['NRPB10'],
    note: 'repeat: TP without the entry only from rptUntil',
    edits: [rxDel('entry settle(', /^\s*require\(tx\.daa >= rptUntil\);\s*$/m)],
  },
  {
    id: 'CB11',
    file: 'KobCondBidKron',
    test: T_RPT,
    expect: ['NRPB14', 'NRPB34'],
    note: 'repeat: entry merge argument names this exit and n (NRPB34: an arming update of the entry, its ev pushed as 0x08 || ev, is no merge)',
    edits: [
      rxDel('entry settle(', /^\s*require\(int\(byte\[8\]\(OpTxInputScriptSigSubstr\(pin, 1, 9\)\)\) == 0 - \(self \* MERGE_K \+ n\)\);\s*$/m),
    ],
  },
  {
    id: 'CB12',
    file: 'KobCondBidKron',
    test: T_RPT,
    expect: ['NRPB11'],
    note: 'repeat: maker profit >= proceeds - spend',
    edits: [rxDel('entry settle(', /^\s*require\(tx\.outputs\[self\]\.value >= proceeds - spend\);\s*$/m)],
  },
  {
    id: 'CB13',
    file: 'KobCondBidKron',
    test: T_RPT,
    expect: ['NRPB12'],
    note: 'repeat: continuation keep == in - proceeds - ceil(prefund of n)',
    edits: [rx('entry settle(', /keep = tx\.inputs\[self\]\.value - proceeds - quoteOf\(n, rptPre, scale - 1\);/, 'keep = 0;')],
  },
  {
    id: 'CB14',
    file: 'KobCondBidKron',
    test: T_NEG,
    expect: ['NB21', 'NB21b'],
    note: 'update: continuation script == contSpk (exact step count, no restart)',
    edits: [
      rxDel('entry update(', /^\s*require\(tx\.outputs\[selfOut\]\.scriptPubKey == contSpk\(newStop, amountLeft, newArmed\)\);\s*$/m),
    ],
  },
  {
    id: 'CB15',
    file: 'KobCondBidKron',
    test: T_NEG,
    expect: ['NB20'],
    note: 'trail: at most once per trailWait (require(this.ageDaa >= trailWait))',
    edits: [rxDel('entry update(', /^\s*require\(this\.ageDaa >= trailWait\);\s*$/m)],
  },
  // ---- KobCondBidKron, new v3 checks
  {
    id: 'CB-minfill',
    file: 'KobCondBidKron',
    test: T_MINFILL,
    expect: ['NV3CB01'],
    note: 'v3: minimum fill (n >= minFill unless n == amountLeft)',
    edits: [rxDel('entry settle(', /^\s*require\(n >= minFill \|\| n == amountLeft\);\s*$/m)],
  },
  {
    id: 'CB-spendround',
    file: 'KobCondBidKron',
    test: T_ROUND,
    expect: ['NV3CB10'],
    note: 'v3: the buy spend is rounded DOWN (the maker pays at most the floor); ceil would let the filler keep one sompi more',
    edits: [rx('entry settle(', /int spend = quoteOf\(n, legPrice \+ tip, 0\);/, 'int spend = quoteOf(n, legPrice + tip, scale - 1);')],
  },
  {
    id: 'CB-updateparent',
    file: 'KobCondBidKron',
    test: T_MERGE,
    expect: ['NV3CB41'],
    note: 'v3: an exit never arms/trails next to its repeat entry (require(OpCovInputCount(parent) == 0))',
    edits: [rxDel('entry update(', /^\s*require\(OpCovInputCount\(parent\) == 0\);\s*$/m)],
  },
  {
    id: 'CB-pin08',
    file: 'KobCondBidKron',
    run: { [T_MERGE]: ['NV3CB42'] },
    inputOnly: ['NV3CB42'], // the crafted entry fails its own 9-byte-push exec; the exit (rearm) input is what flips
    note: 'v3: the repeat entry pin starts with the 8-byte merge push (0x08); a 9-byte push whose low 8 bytes alias the merge argument passes the value check but not this one',
    edits: [rxDel('entry settle(', /^\s*require\(OpTxInputScriptSigSubstr\(pin, 0, 1\) == byte\[\]\(0x08\)\);\s*$/m)],
  },
  // ---- KobIfdAskKron
  {
    id: 'IA1',
    file: 'KobIfdAskKron',
    run: { [T_DUST]: ['NS15b'], [T_RPT]: ['NRPB25'] },
    note: 'settle: custody holds exactly amountLeft base units (amount check)',
    edits: [rxDel('entry settle(', /^\s*require\(int\(byte\[8\]\(tin\.slice\(36, 44\)\)\) == tinAmount\);\s*$/m)],
  },
  {
    id: 'IA2',
    file: 'KobIfdAskKron',
    run: { [T_LIFE]: ['NS13', 'NS14'], [T_RPT]: ['NRPB24', 'NRPB24b'] },
    note: 'settle: noStrays(selfId, custody) call',
    edits: [rxDel('entry settle(', /^\s*noStrays\(selfId, custody\);\s*$/m)],
  },
  {
    id: 'IA2b',
    file: 'KobIfdAskKron',
    test: T_NEG,
    expect: ['KI-P3b'],
    inputOnly: ['KI-P3b'],
    note: 'noStrays: scan bound require(cnt <= MAX_TOK_IN)',
    edits: [rxDel('function noStrays', /^\s*require\(cnt <= MAX_TOK_IN\);\s*$/m)],
  },
  {
    id: 'IA3',
    file: 'KobIfdAskKron',
    run: { [T_LIFE]: ['NI22'], [T_AA]: ['NTL23'] },
    note: 'update refuses token inputs owned by the entry (touch: the evidence fill brings foreign token inputs)',
    edits: [rxDel('entry update(', /^\s*noStrays\(selfId, -1\);$/m)],
  },
  {
    id: 'IA4',
    file: 'KobIfdAskKron',
    test: T_RPT,
    expect: ['NRPB28'],
    note: 'close: require(OpCovInputCount(tokenCovId) == 0)',
    edits: [rxDel('entry close()', /^\s*require\(OpCovInputCount\(tokenCovId\) == 0\);\s*$/m)],
  },
  {
    id: 'IA5',
    file: 'KobIfdAskKron',
    test: T_RPT,
    expect: ['NRPB26'],
    note: 'close: require(amountLeft == 0)',
    edits: [rxDel('entry close()', /^\s*require\(amountLeft == 0\);\s*$/m)],
  },
  {
    id: 'IA6',
    file: 'KobIfdAskKron',
    test: T_RPT,
    expect: ['NRPB27'],
    note: 'close: not before soft expiry / idle bound',
    edits: [rxDel('entry close()', /^\s*require\(tx\.daa >= idleEnd\);\s*$/m)],
  },
  {
    id: 'IA7',
    file: 'KobIfdAskKron',
    test: T_LIFE,
    expect: ['NI23'],
    note: 'update: keeper takes at most keeperTip',
    edits: [rx('entry update(', /tx\.outputs\[c\]\.value >= tx\.inputs\[self\]\.value - keeperTip/, 'tx.outputs[c].value >= 0')],
  },
  {
    id: 'IA8',
    file: 'KobIfdAskKron',
    test: T_LIFE,
    expect: ['NI15', 'NI16', 'NI17'],
    note: 'stop entry: unarmed fill reads its trigger evidence (touch)',
    edits: [rxDel('entry settle(', /^\s*require\(touchAsk\(ev, tk\) <= entryStop\);\s*$/m)],
  },
  {
    id: 'IA8c',
    file: 'KobIfdAskKron',
    run: { [T_LIFE]: ['NI17'], [T_AF]: ['NTK19'] },
    note: 'settle, unarmed stop entry: the evidence ask quotes <= entryStop',
    edits: [rx('entry settle(', /require\(touchAsk\(ev, tk\) <= entryStop\);/, 'require(touchAsk(ev, tk) >= 0);')],
  },
  {
    id: 'TK-auc',
    file: 'KobIfdAskKron',
    test: T_LIFE,
    expect: ['NI18b'],
    note: 'sell-stop entry armed inside its fill with an auction: the fill sells at the stop (the auction opens at the trigger)',
    edits: [rxDel('if (armed == 0) {', /if \(bandDaa > 0\) \{\s*p = entryStop;\s*\}/)],
  },
  {
    id: 'IA9',
    file: 'KobIfdAskKron',
    test: T_LIFE,
    expect: ['NI21'],
    note: 'stop entry: require(entryStop >= price)',
    edits: [rxDel('entry settle(', /^\s*require\(entryStop >= price\);\s*$/m)],
  },
  {
    id: 'IA10',
    file: 'KobIfdAskKron',
    test: T_LIFE,
    expect: ['NI20'],
    note: 'minFill: require(n >= minFill || outAmount == 0)',
    edits: [rxDel('entry settle(', /^\s*require\(n >= minFill \|\| outAmount == 0\);\s*$/m)],
  },
  {
    id: 'IA11',
    file: 'KobIfdAskKron',
    run: { [T_LIFE]: ['NI18'], [T_NEG]: ['NI6'] },
    note: 'exit funded with proceeds + prefund + carrier (auction price paid)',
    edits: [rxDel('entry settle(', /^\s*require\(tx\.outputs\[exitOut\]\.value >= proceeds \+ pre \+ exitCarrier\);\s*$/m)],
  },
  {
    id: 'IA12',
    file: 'KobIfdAskKron',
    run: { [T_LIFE]: ['NI19'], [T_RPT]: ['NRPB3', 'NRPB19', 'NRPB19b', 'NRPB19c', 'NRPB19d'] },
    note: 'continuation script == contSpk (auction origin, cycle count, amount, unarmed re-arm)',
    edits: [rxDel('entry settle(', /^\s*require\(tx\.outputs\[c\]\.scriptPubKey == contSpk\(newArmed, newLeft, newRpt\)\);\s*$/m)],
  },
  {
    id: 'IA13',
    file: 'KobIfdAskKron',
    test: T_RPT,
    expect: ['NRPB6'],
    note: 'booking time: require(tx.daa >= t) before dating rptUntil',
    edits: [rxDel('if (rptAmount > n)', /^\s*require\(tx\.daa >= t\);\s*$/m)],
  },
  {
    id: 'IA14',
    file: 'KobIfdAskKron',
    test: T_RPT,
    expect: ['NRPB3'],
    note: 'booking: rptAmount decremented by n',
    edits: [rx('if (rptAmount > n)', /newRpt = rptAmount - n;/, 'newRpt = rptAmount;')],
  },
  {
    id: 'IA15',
    file: 'KobIfdAskKron',
    test: T_RPT,
    expect: ['NRPB7'],
    note: 'repeating entry never terminates on a fill (outAmount > 0 || rptAmount > 0)',
    edits: [rx('entry settle(', /if \(outAmount > 0 \|\| rptAmount > 0\) \{/, 'if (outAmount > 0) {')],
  },
  {
    id: 'IA16',
    file: 'KobIfdAskKron',
    test: T_RPT,
    expect: ['NRPB8'],
    note: 'sold-out repeating entry keeps the custody carrier (floor + tokenIn value)',
    edits: [rxDel('entry settle(', /^\s*floor = floor \+ tx\.inputs\[tokenIn\]\.value;\s*$/m)],
  },
  {
    id: 'IA17',
    file: 'KobIfdAskKron',
    test: T_RPT,
    hold: { [T_RPT]: ['NRPB20'] },
    note: 'merge: exit parent == this entry (part of the exit-tail comparison with rate; a plain exit also fails on rate, so removing the parent alone holds)',
    edits: [rep('byte[](0x20) + byte[](selfId) + byte[](0x08)', 'byte[](0x20) + x.slice(289, 321) + byte[](0x08)')],
  },
  {
    id: 'IA18',
    file: 'KobIfdAskKron',
    test: T_RPT,
    hold: { [T_RPT]: ['NRPB21'] },
    note: 'merge: input k is a genuine KobCondBidKron (template + P2SH check) (the crafted input also fails the exit-terms comparison, so removing the template check alone holds)',
    edits: [
      rx('entry settle(', /byte\[\] x = tplState\(k, COND_BID_PRE, EXIT_STATE_LEN, COND_BID_SUF, COND_BID_TPL\);/, 'int bxs = OpTxInputScriptSigLen(k) - (COND_BID_PRE + EXIT_STATE_LEN + COND_BID_SUF); byte[] x = OpTxInputScriptSigSubstr(k, bxs + COND_BID_PRE, bxs + COND_BID_PRE + EXIT_STATE_LEN);'),
    ],
  },
  {
    id: 'IA19',
    file: 'KobIfdAskKron',
    test: T_RPT,
    expect: ['NRPB15'],
    note: 'merge: partial buy-back, entry re-armed with ceil(prefund of m)',
    edits: [rx('entry settle(', /floor = tx\.inputs\[self\]\.value \+ quoteOf\(m, prefund, scale - 1\);/, 'floor = 0;')],
  },
  {
    id: 'IA20',
    file: 'KobIfdAskKron',
    test: T_RPT,
    expect: ['NRPB16'],
    note: 'merge: sell-out leftovers come back (floor with the exit value)',
    edits: [rep('if (all > floor) { floor = all; }', 'floor = 0;')],
  },
  {
    id: 'IA21',
    file: 'KobIfdAskKron',
    test: T_RPT,
    expect: ['NRPB16b', 'NRPB16c'],
    note: 'merge: custody carrier kept (tokOut value >= keepCarrier)',
    edits: [rxDel('entry settle(', /^\s*require\(tx\.outputs\[tokOut\]\.value >= keepCarrier\);\s*$/m)],
  },
  {
    id: 'IA22',
    file: 'KobIfdAskKron',
    test: T_RPT,
    expect: ['NRPB17', 'NRPB18'],
    note: 'token output pin (custody / remainder / refund state: owner, amount, type)',
    edits: [rxDel('// Pin the only token output', /require\(tx\.outputs\[outIdx\]\.scriptPubKey == [\s\S]*?\)\)\);/)],
  },
  {
    id: 'IA23',
    file: 'KobIfdAskKron',
    test: T_RPT,
    expect: ['NRPB19d'],
    note: 'merge into an empty stop entry re-arms unarmed (newArmed = 0)',
    edits: [rxDel(`if (amountLeft == 0) {
                    newArmed`, /^\s*newArmed = 0;\s*$/m)],
  },
  {
    id: 'IA24',
    file: 'KobIfdAskKron',
    run: { [T_RPT]: ['NRPB1', 'NRPB2', 'NRPB4', 'NRPB4b', 'NRPB5'], [T_NEG]: ['NI1', 'NI2', 'NI2b', 'NI3', 'NI3b', 'NI5'] },
    note: 'booking, both binds of the exit removed: exit script equality AND exit genesis id (NI4 is rejected by the covenant rules independently of both)',
    edits: [
      rxDel('entry settle(', /^\s*require\(tx\.outputs\[exitOut\]\.scriptPubKey == exitSpk\);\s*$/m),
      rxDel('entry settle(', /^\s*require\(OpOutputCovenantId\(exitOut\) == blake2bWithKey\([\s\S]*?byte\[\]\("CovenantID"\)\s*\)\);\s*$/m),
    ],
  },
  {
    id: 'IA24a',
    file: 'KobIfdAskKron',
    hold: { [T_RPT]: ['NRPB1', 'NRPB4', 'NRPB5'], [T_NEG]: ['NI1', 'NI2', 'NI2b'] },
    note: 'ONLY the exit script equality removed: the genesis id binds the exit script too (defence in depth)',
    edits: [rxDel('entry settle(', /^\s*require\(tx\.outputs\[exitOut\]\.scriptPubKey == exitSpk\);\s*$/m)],
  },
  {
    id: 'IA24b',
    file: 'KobIfdAskKron',
    run: { [T_NEG]: ['NI3', 'NI3b', 'NI5'] },
    hold: { [T_RPT]: ['NRPB1', 'NRPB4', 'NRPB5'], [T_NEG]: ['NI1', 'NI2', 'NI2b'] },
    note: 'ONLY the exit genesis id removed: double / aliased / attacker-authorised exits are accepted; the script equality still binds the tampered / plain / altered exits',
    edits: [rxDel('entry settle(', /^\s*require\(OpOutputCovenantId\(exitOut\) == blake2bWithKey\([\s\S]*?byte\[\]\("CovenantID"\)\s*\)\);\s*$/m)],
  },
  // ---- KobIfdAskKron, new v3 checks
  {
    id: 'IA-minfill',
    file: 'KobIfdAskKron',
    test: T_MINFILL,
    expect: ['NV3IA01'],
    note: 'v3: minimum fill (n >= minFill unless the fill sells out)',
    edits: [rxDel('entry settle(', /^\s*require\(n >= minFill \|\| outAmount == 0\);\s*$/m)],
  },
  {
    id: 'IA-procround',
    file: 'KobIfdAskKron',
    test: T_ROUND,
    expect: ['NV3IA10'],
    note: 'v3: the exit proceeds are rounded UP (ceil, the maker receives at least the exact value)',
    edits: [rx('entry settle(', /int proceeds = quoteOf\(n, p - tip, scale - 1\);/, 'int proceeds = quoteOf(n, p - tip, 0);')],
  },
  {
    id: 'IA-preround',
    file: 'KobIfdAskKron',
    test: T_ROUND,
    expect: ['NV3IA11'],
    note: 'v3: the exit prefund is rounded UP (ceil)',
    edits: [rx('entry settle(', /int pre = quoteOf\(n, prefund, scale - 1\);/, 'int pre = quoteOf(n, prefund, 0);')],
  },
  {
    id: 'IA-mergeround',
    file: 'KobIfdAskKron',
    test: T_ROUND,
    expect: ['NV3IA12'],
    note: 'v3: a re-arming buy-back returns at least ceil(prefund of m) to the entry',
    edits: [
      rx('entry settle(', /floor = tx\.inputs\[self\]\.value \+ quoteOf\(m, prefund, scale - 1\);/, 'floor = tx.inputs[self].value + quoteOf(m, prefund, 0);'),
    ],
  },
  {
    id: 'IA-pricetip',
    file: 'KobIfdAskKron',
    test: T_TIP,
    expect: ['NV3IA21'],
    note: 'v3: a sell entry requires price >= tip (so p >= price >= tip; a booked rptPrice = price - tip is never negative)',
    edits: [rxDel('entry settle(', /^\s*require\(price >= tip\);\s*$/m)],
  },
  {
    id: 'IA-k08',
    file: 'KobIfdAskKron',
    run: { [T_MERGE]: ['NV3IA40'] },
    inputOnly: ['NV3IA40'], // the crafted exit fails its own 9-byte-push exec; the entry (merge) input is what flips
    hold: { [T_RPT]: ['NRPB32'] }, // a cancelled exit is still refused by the value check (== m)
    note: 'v3: the booked exit at k starts with the 8-byte fill push (0x08); a 9-byte push whose low 8 bytes alias m passes the value check and the exit-terms comparison but not this one',
    edits: [rxDel('entry settle(', /^\s*require\(OpTxInputScriptSigSubstr\(k, 0, 1\) == byte\[\]\(0x08\)\);\s*$/m)],
  },
  // ---- fix pass
  {
    id: 'FXL3c',
    file: 'KobIfdAskKron',
    test: T_RPT,
    expect: ['NRPB29'],
    note: 'the merge requires the exit terms [0..190) (maker, legs) to be the committed exitState',
    edits: [rxDel('entry settle(', /^\s*require\(x\.slice\(0, 190\) == st\.slice\(0, 190\)\);\s*$/m)],
  },
  {
    id: 'FXL3d',
    file: 'KobIfdAskKron',
    test: T_RPT,
    expect: ['NRPB30'],
    note: 'the merge requires parent = this entry, rptPrice and rptPre = its own (exit tail [288..340))',
    edits: [rxDel('int rate = price - tip;', /^\s*require\(x\.slice\(288, 340\) == [\s\S]*?\);$/m)],
  },
  {
    id: 'FXL3e',
    file: 'KobIfdAskKron',
    test: T_RPT,
    expect: ['NRPB33'],
    inputOnly: ['NRPB33'], // v3: the exit's update also fails its own parent guard; the entry (merge) input is what flips
    hold: { [T_RPT]: ['NRPB32'] }, // v3: a cancelled exit (65-byte sig push) is also refused by the 0x08 first-byte check
    note: 'the merge requires the exit to run its settle with n = m (sigscript [1..9)); NRPB33: an arming update of the exit whose ev is pushed as 0x08 || ev is no settle',
    edits: [rxDel('entry settle(', /^\s*require\(int\(byte\[8\]\(OpTxInputScriptSigSubstr\(k, 1, 9\)\)\) == m\);\s*$/m)],
  },
  {
    id: 'FXL3f',
    file: 'KobIfdAskKron',
    test: T_RPT,
    expect: ['NRPB31'],
    note: 'a sell-out merge never costs the entry (floor = max(prefund, exit value - proceeds))',
    edits: [rep('if (all > floor) { floor = all; }', 'floor = all;')],
  },
  // ---- touch trigger: KobCondBidKron touchBid (buy-stop leg armed inside its fill), touch (update: arm / trail)
  ...touchMutations({
    prefix: 'TB',
    file: 'KobCondBidKron',
    fn: 'function touchBid(int ev) : int {',
    what: 'touchBid (settle, buy-stop leg)',
    runs: {
      push08: { [T_BS]: ['NTB10'] },
      npos: { run: { [T_BS]: ['NTB11b'] }, inputOnly: ['NTB11b'] },
      tpl: { [T_BS]: ['NTB17'] },
      p2sh: { [T_BS]: ['NTB18'] },
      token: { [T_BS]: ['NTB07'] },
      scale: { [T_BS]: ['NTB08'] },
      mintouch: { [T_BS]: ['NTB09'] },
      slope: { [T_BS]: ['NTB05'] },
      cltv: { [T_BS]: ['NTB01', 'NTB03', 'NTB04'] },
      interval: { [T_BS]: ['NTB04'] },
      active: { [T_BS]: ['NTB03'] },
    },
  }),
  {
    id: 'TB-rule',
    file: 'KobCondBidKron',
    run: { [T_BS]: ['NTB19'], [T_NEG]: ['NB13'] },
    note: 'settle, unarmed buy-stop leg: the evidence bid quotes >= stopPrice',
    edits: [rxDel('    entry settle(', /^\s*require\(rp >= stopPrice\);$/m)],
  },
  ...touchMutations({
    prefix: 'TV',
    file: 'KobCondBidKron',
    fn: 'function touch(int ev, int tk) : (int, int) {',
    what: 'touch (update: arm on a bid, trail on an ask)',
    runs: {
      push08: { [T_BA]: ['NTV10', 'NTV11'], [T_BT]: ['NTW10'] },
      npos: { [T_BT]: ['NTW11'] },
      tpl: { [T_BA]: ['NTV17'], [T_BT]: ['NTW17'] },
      p2sh: { [T_BA]: ['NTV18'], [T_BT]: ['NTW18'] },
      token: { [T_BA]: ['NTV07'], [T_BT]: ['NTW07b'] },
      scale: { [T_BA]: ['NTV08'], [T_BT]: ['NTW08'] },
      mintouch: { [T_BA]: ['NTV09'], [T_BT]: ['NTW09'] },
      slope: { [T_BA]: ['NTV05'], [T_BT]: ['NTW05'] },
      cltv: { [T_BA]: ['NTV01', 'NTV03', 'NTV04'], [T_BT]: ['NTW01', 'NTW02', 'NTW03', 'NTW04'] },
      interval: { [T_BA]: ['NTV04'], [T_BT]: ['NTW04'] },
      active: { [T_BA]: ['NTV03'], [T_BT]: ['NTW03'] },
      tokdaa: { [T_BT]: ['NTW02'] },
      tkcov: { [T_BT]: ['NTW02b'] },
      owner: { [T_BT]: ['NTW15', 'NTW16'] },
    },
  }),
  {
    id: 'TV-rule',
    file: 'KobCondBidKron',
    test: T_BA,
    expect: ['NTV19'],
    note: 'update, arm: the evidence bid quotes >= stopPrice',
    edits: [rxDel('    entry update(int ev, int tk) {', /^\s*require\(rp >= stopPrice\);$/m)],
  },
  {
    id: 'TW-k',
    file: 'KobCondBidKron',
    test: T_BT,
    expect: ['NTW19', 'NTW19b'],
    note: 'update, trail: the evidence ask justifies k >= 1 steps (k = 0 drains keeperTip and resets trailWait, k < 0 moves the stop up)',
    edits: [del('            require(k >= 1);\n')],
  },
  {
    id: 'TW-step',
    file: 'KobCondBidKron',
    hold: { [T_NEG]: ['NB24'], [T_BA]: ['NTV06'] },
    note: 'update, trail: trailStep > 0 (a non-trailing order divides by trailStep = 0 and fails anyway)',
    edits: [del('            require(trailStep > 0);\n')],
  },
  {
    id: 'TV-armed',
    file: 'KobCondBidKron',
    test: T_NEG,
    expect: ['NB19'],
    note: 'update only while unarmed',
    edits: [rxDel('    entry update(int ev, int tk) {', /^\s*require\(armed == 0\);$/m)],
  },
  // ---- touch trigger: KobIfdAskKron touchAsk (sell-stop entry armed inside its fill or by update)
  ...touchMutations({
    prefix: 'TK',
    file: 'KobIfdAskKron',
    fn: 'function touchAsk(int ev, int tk) : int {',
    what: 'touchAsk (sell-stop entry)',
    runs: {
      push08: { [T_AF]: ['NTK10'], [T_AA]: ['NTL10'] },
      npos: { [T_AF]: ['NTK11'], [T_AA]: ['NTL11'] },
      tpl: { [T_AF]: ['NTK17'], [T_AA]: ['NTL17'] },
      p2sh: { [T_AF]: ['NTK18'], [T_AA]: ['NTL18'] },
      token: { [T_AF]: ['NTK07b'], [T_AA]: ['NTL07b'] },
      scale: { [T_AF]: ['NTK08'], [T_AA]: ['NTL08'] },
      mintouch: { [T_AF]: ['NTK09'], [T_AA]: ['NTL09'] },
      slope: { [T_AF]: ['NTK05'], [T_AA]: ['NTL05'] },
      cltv: { [T_AF]: ['NTK01', 'NTK02', 'NTK03', 'NTK04'], [T_AA]: ['NTL01', 'NTL02', 'NTL03', 'NTL04'] },
      interval: { [T_AF]: ['NTK04'], [T_AA]: ['NTL04'] },
      active: { [T_AF]: ['NTK03'], [T_AA]: ['NTL03'] },
      tokdaa: { [T_AF]: ['NTK02'], [T_AA]: ['NTL02'] },
      tkcov: { [T_AF]: ['NTK02b'], [T_AA]: ['NTL02b'] },
      owner: { [T_AF]: ['NTK15', 'NTK16'], [T_AA]: ['NTL15', 'NTL16'] },
    },
  }),
  {
    id: 'TL-rule',
    file: 'KobIfdAskKron',
    test: T_AA,
    expect: ['NTL19'],
    note: 'update: the evidence ask quotes <= entryStop',
    edits: [rx('    entry update(int ev, int tk) {', /require\(touchAsk\(ev, tk\) <= entryStop\);/, 'require(touchAsk(ev, tk) >= 0);')],
  },
  {
    id: 'TL-amount',
    file: 'KobIfdAskKron',
    test: T_AA,
    expect: ['NTL24'],
    note: 'update: the entry has base units to fill (an empty repeating entry would pay keeperTip for a useless arm)',
    edits: [rxDel('    entry update(int ev, int tk) {', /^\s*require\(amountLeft > 0\);$/m)],
  },
  {
    id: 'TL-limit',
    file: 'KobIfdAskKron',
    test: T_AA,
    expect: ['NTL25'],
    note: "update: the stop is on the limit's side (entryStop >= price; else no fill can follow the arm)",
    edits: [rxDel('    entry update(int ev, int tk) {', /^\s*require\(entryStop >= price\);$/m)],
  },
  {
    id: 'TL-origin',
    file: 'KobIfdAskKron',
    test: T_RPT,
    expect: ['NRPB35'],
    note: 'merge into an entry armed by update (armed 1, band): the continuation records the band origin (else the auction restarts)',
    edits: [rep('if (armed == 1 && bandDaa > 0) {', 'if (armed == 1 && bandDaa < 0) {')],
  },
  // ---- 2026-10-06: the refund of an empty (repeating) entry
  {
    id: 'IA-refund-held',
    file: 'KobIfdAskKron',
    test: 'kron_empty_repeating_ifda_refund_is_refused',
    expect: ['SR2'],
    inputOnly: ['SR2'],
    note: 'refund (settle nb = 0) only while tokens are held: an empty repeating entry with a zero-amount custody would pin no output, so close() is its end (inputOnly: whether the KRON program itself takes the zero-amount custody is not what this check decides)',
    edits: [rxDel('    entry settle(byte[8] nb, int tokenIn,', /^\s*require\(amountLeft > 0\);$/m)],
  },
];
