//! Compute-budget table.
//!
//! A version-1 input commits a compute budget (units of 10,000 script units, the first 9,999 free);
//! consensus rejects the input if its script needs more, and every budget unit costs 100 grams of
//! compute mass. KOB clients do not run the script engine to pick budgets: they look up the input's
//! **role** (template, entry, branch, token slot shape) in `data/compute_budgets.json`, which is
//! generated by running every builder shape through the rusty-kaspa v2.1.0 engine
//! (`tests/budget_table.rs`, `KOB_REGEN=1` to rewrite) and verified by the same test on every run.
//!
//! An input's cost depends on the transaction around it (an order covenant pays for every other
//! token input of the batch), so the generator measures every scenario also inside the largest
//! batches the builders accept and keeps the maximum per role; the table is exact at that worst
//! shape (one unit less is rejected there), which over-provisions a smaller batch by at most one
//! unit. [`crate::tx::finalize`] can tighten every budget to the exact minimum after signing (the
//! sighash does not commit to budgets).

use std::collections::BTreeMap;
use std::sync::OnceLock;

use kaspa_consensus_core::mass::{ComputeBudget, ScriptUnits};

use crate::error::{Error, Result};

const TABLE_JSON: &str = include_str!("../data/compute_budgets.json");

/// The committed table (role -> budget).
pub fn table() -> &'static BTreeMap<String, u16> {
    static T: OnceLock<BTreeMap<String, u16>> = OnceLock::new();
    T.get_or_init(|| serde_json::from_str(TABLE_JSON).expect("compute budget table json"))
}

/// Budget for an input role.
pub fn lookup(role: &str) -> Result<u16> {
    table().get(role).copied().ok_or_else(|| Error::MissingBudget(role.to_string()))
}

/// Smallest budget whose allowance covers `units` script units.
pub fn budget_for_units(units: u64) -> u16 {
    ComputeBudget::checked_covering_script_units(ScriptUnits(units)).map(|b| b.value()).unwrap_or(u16::MAX)
}
