//! KCC-20 token program parameters used when KOB issues a fixed-supply token.
//!
//! The reference KCC-20 program (argent kcc20-reference PR #1, `contracts/kcc20/KCC20Ref.sil`)
//! accepts at most 3 token inputs and 3 token outputs per transfer. Those bounds are compile-time
//! constants of the generated program, so they are fixed per token at issuance and every later
//! transfer of that token pays for them (the whole program is pushed in every token input's
//! sigscript). See `crates/kob-tests/tests/kcc20_limits_tests.rs` for the measurements behind the
//! default below.

/// KOB-issued tokens use the reference KCC-20 program with a non-default slot configuration
/// ([`ISSUE_MAX_TOKEN_INPUTS`] / [`ISSUE_MAX_TOKEN_OUTPUTS`], allowed by KCC-20 "non-default
/// configuration"). Proposal P2 (holders on the 3/3 program plus a matcher-held batch leader,
/// `contracts/kcc20/p2/`, tested in `crates/kob-tests/tests/kcc20_p2_tests.rs`) is implemented
/// for the upstream proposal at launch but is NOT used for issuance until KCC-20 adopts it.
pub const ISSUE_USE_P2_BATCH_LEADER: bool = false;
/// Holder inputs and outputs a P2 batch leader can process in one transaction.
pub const P2_BATCH_SLOTS: usize = 16;
/// Maximum token inputs per transfer for tokens issued by KOB tooling.
pub const ISSUE_MAX_TOKEN_INPUTS: usize = 8;
/// Maximum token outputs per transfer for tokens issued by KOB tooling.
pub const ISSUE_MAX_TOKEN_OUTPUTS: usize = 8;

/// Errors raised while deriving a KCC-20 source with non-default slot limits.
#[derive(Debug, thiserror::Error)]
pub enum Kcc20LimitError {
    /// Limits must allow at least one input and one output.
    #[error("max token inputs and outputs must be >= 1 (got {0} / {1})")]
    ZeroLimit(usize, usize),
    /// The base source does not contain the expected generated pattern exactly once.
    #[error("base KCC-20 source does not contain `{0}` exactly once (not the reference program?)")]
    Pattern(&'static str),
}

/// Derive the reference KCC-20 program with `max_inputs` token inputs (leader plus
/// `max_inputs - 1` delegators) and `max_outputs` token outputs per transfer.
///
/// Only `MAX_DELEGATES`, `MAX_TOKEN_OUTPUTS` and the two literal bounds that argentc emits for
/// them change. `(3, 3)` returns the base source unchanged. Any other value also gets a
/// provenance header so the file is never mistaken for the upstream program.
pub fn kcc20_source_with_limits(base: &str, max_inputs: usize, max_outputs: usize) -> Result<String, Kcc20LimitError> {
    if max_inputs == 0 || max_outputs == 0 {
        return Err(Kcc20LimitError::ZeroLimit(max_inputs, max_outputs));
    }
    if (max_inputs, max_outputs) == (3, 3) {
        return Ok(base.to_string());
    }
    let d = max_inputs - 1;
    let o = max_outputs;
    let reps: [(&'static str, String); 6] = [
        ("int constant MAX_DELEGATES = 2;", format!("int constant MAX_DELEGATES = {d};")),
        ("int constant MAX_TOKEN_OUTPUTS = 3;", format!("int constant MAX_TOKEN_OUTPUTS = {o};")),
        ("require(gen__delegates_count <= 2);", format!("require(gen__delegates_count <= {d});")),
        (
            "for (gen__delegates_position, 0, gen__delegates_count, 2) {",
            format!("for (gen__delegates_position, 0, gen__delegates_count, {d}) {{"),
        ),
        ("require(gen__next_outputs_output_count <= 3);", format!("require(gen__next_outputs_output_count <= {o});")),
        (
            "for (gen__next_outputs_output_position, 0, gen__next_outputs_output_count, 3) {",
            format!("for (gen__next_outputs_output_position, 0, gen__next_outputs_output_count, {o}) {{"),
        ),
    ];
    let mut s = base.to_string();
    for (from, to) in reps.iter() {
        if s.matches(from).count() != 1 {
            return Err(Kcc20LimitError::Pattern(from));
        }
        s = s.replacen(from, to, 1);
    }
    const PRAGMA: &str = "pragma silverscript ^0.1.0;\n";
    let body = s.strip_prefix(PRAGMA).ok_or(Kcc20LimitError::Pattern("pragma silverscript ^0.1.0;"))?;
    Ok(format!(
        "{PRAGMA}// KOB variant (not upstream): max {max_inputs} token inputs / {max_outputs} token outputs per transfer. Only\n\
         // MAX_DELEGATES, MAX_TOKEN_OUTPUTS and the two matching literal loop/require bounds differ from\n\
         // ../KCC20Ref.sil. Generated by kob_protocol::kcc20::kcc20_source_with_limits.\n{body}"
    ))
}

const P2_CTOR_FROM: &str = "contract KCC20(\n";
const P2_CTOR_TO: &str = "contract KCC20(\n    byte[32] B_TPL,\n    int B_PRE,\n    int B_SUF,\n";
const P2_LEADER_READ: &str = concat!(
    "        // :: direct input state (single-actor covenant has one template)\n",
    "        State gen__leader_state = readInputState(gen__leader_input_idx);\n"
);
const P2_ALLOWLIST: &str = r#"        // :: KOB P2 leader allowlist: the leader is this template or the batch-leader template
        int kob__size = this.bytecodeSize;
        int kob__own_len = OpTxInputScriptSigLen(this.activeInputIndex);
        byte[] kob__own = OpTxInputScriptSigSubstr(this.activeInputIndex, kob__own_len - kob__size, kob__own_len);
        int kob__lead_len = OpTxInputScriptSigLen(gen__leader_input_idx);
        byte[] kob__lead = OpTxInputScriptSigSubstr(gen__leader_input_idx, kob__lead_len - kob__size, kob__lead_len);
        bool kob__same = tx.inputs[gen__leader_input_idx].scriptPubKey == byte[](new ScriptPubKeyP2SHFromRedeemScript(kob__lead))
            && kob__lead.slice(0, 1) == kob__own.slice(0, 1)
            && kob__lead.slice(113, kob__size) == kob__own.slice(113, kob__size);
        if (!kob__same) {
            int kob__bsize = B_PRE + 126 + B_SUF;
            byte[] kob__b = OpTxInputScriptSigSubstr(gen__leader_input_idx, kob__lead_len - kob__bsize, kob__lead_len);
            require(tx.inputs[gen__leader_input_idx].scriptPubKey == byte[](new ScriptPubKeyP2SHFromRedeemScript(kob__b)));
            require(
                blake3(byte[](B_PRE as byte[8]) + kob__b.slice(0, B_PRE) + byte[](B_SUF as byte[8]) + kob__b.slice(B_PRE + 126, kob__bsize))
                    == B_TPL
            );
        }
"#;
const P2_HEADER: &str = "// KOB variant (not upstream): proposal P2 holder program. Identical to ../KCC20Ref.sil except\n\
// that the delegator path accepts a leader only if it is this template or the KCC20Batch\n\
// batch-leader template (constructor constants B_TPL / B_PRE / B_SUF), replacing the unused\n\
// direct read of the leader state. Generated by kob_protocol::kcc20::kcc20_p2_holder_source.\n";

/// Derive the proposal-P2 holder program from the reference KCC-20 program.
///
/// Two changes, both in generated code patterns that must occur exactly once: the constructor gains
/// the batch-leader template constants (`B_TPL`, `B_PRE`, `B_SUF`), and the delegator path replaces
/// its unused direct read of the leader state with a two-entry allowlist: the leader must be this
/// template (same prefix and suffix, P2SH checked) or the batch-leader template (blake3 template
/// hash). The leader path, limits (3/3) and state layout are unchanged.
pub fn kcc20_p2_holder_source(base: &str) -> Result<String, Kcc20LimitError> {
    let base = base.replace("\r\n", "\n");
    for (pat, name) in [(P2_CTOR_FROM, "contract KCC20("), (P2_LEADER_READ, "readInputState(gen__leader_input_idx)")] {
        if base.matches(pat).count() != 1 {
            return Err(Kcc20LimitError::Pattern(name));
        }
    }
    let s = base.replacen(P2_CTOR_FROM, P2_CTOR_TO, 1).replacen(P2_LEADER_READ, P2_ALLOWLIST, 1);
    const PRAGMA: &str = "pragma silverscript ^0.1.0;\n";
    let body = s.strip_prefix(PRAGMA).ok_or(Kcc20LimitError::Pattern("pragma silverscript ^0.1.0;"))?;
    Ok(format!("{PRAGMA}{P2_HEADER}{body}"))
}

const OPT_ALLOWLIST: &str = r#"        // :: KOB optional batch leader: the leader is this template, or the committed batch-leader template (B_PRE > 0; all zeros = none)
        int kob__size = this.bytecodeSize;
        int kob__own_len = OpTxInputScriptSigLen(this.activeInputIndex);
        byte[] kob__own = OpTxInputScriptSigSubstr(this.activeInputIndex, kob__own_len - kob__size, kob__own_len);
        int kob__lead_len = OpTxInputScriptSigLen(gen__leader_input_idx);
        bool kob__same = false;
        if (kob__lead_len >= kob__size) {
            byte[] kob__lead = OpTxInputScriptSigSubstr(gen__leader_input_idx, kob__lead_len - kob__size, kob__lead_len);
            kob__same = tx.inputs[gen__leader_input_idx].scriptPubKey == byte[](new ScriptPubKeyP2SHFromRedeemScript(kob__lead))
                && kob__lead.slice(0, 1) == kob__own.slice(0, 1)
                && kob__lead.slice(113, kob__size) == kob__own.slice(113, kob__size);
        }
        if (!kob__same) {
            require(B_PRE > 0);
            int kob__bsize = B_PRE + 126 + B_SUF;
            byte[] kob__b = OpTxInputScriptSigSubstr(gen__leader_input_idx, kob__lead_len - kob__bsize, kob__lead_len);
            require(tx.inputs[gen__leader_input_idx].scriptPubKey == byte[](new ScriptPubKeyP2SHFromRedeemScript(kob__b)));
            require(
                blake3(byte[](B_PRE as byte[8]) + kob__b.slice(0, B_PRE) + byte[](B_SUF as byte[8]) + kob__b.slice(B_PRE + 126, kob__bsize))
                    == B_TPL
            );
        }
"#;
const OPT_HEADER: &str = "// KOB variant (not upstream): optional batch leader. Identical to ../KCC20Ref.sil except that the\n\
// delegator path checks its leader: the leader must be this template (P2SH checked, same prefix and\n\
// suffix) or the batch-leader template committed by the constructor constants B_TPL / B_PRE / B_SUF\n\
// (KOB template hash and prefix / suffix lengths of a leader with a 126-byte state, such as\n\
// KCC20Batch.sil). All zeros disables the batch leader (the program tests B_PRE > 0). Generated by\n\
// kob_protocol::kcc20::kcc20_opt_holder_source.\n";

/// Derive the optional-batch-leader holder program (`contracts/kcc20/p2/KCC20Opt.sil`) from the reference KCC-20
/// program.
///
/// Same two edits as [`kcc20_p2_holder_source`] (constructor constants `B_TPL`, `B_PRE`, `B_SUF` before the state
/// fields; the delegator's unused direct read of the leader state replaced by a leader check), with two differences
/// in the check: an all-zero commitment disables the batch-leader branch explicitly (`B_PRE > 0` is required, so the
/// leader must then be this template, without relying on the hash comparison), and the same-template comparison runs
/// only when the leader's signature script is long enough to hold this program, so a committed leader shorter than the
/// holder program is still recognised. The leader path, limits (3/3) and state layout are unchanged.
pub fn kcc20_opt_holder_source(base: &str) -> Result<String, Kcc20LimitError> {
    let base = base.replace("\r\n", "\n");
    for (pat, name) in [(P2_CTOR_FROM, "contract KCC20("), (P2_LEADER_READ, "readInputState(gen__leader_input_idx)")] {
        if base.matches(pat).count() != 1 {
            return Err(Kcc20LimitError::Pattern(name));
        }
    }
    let s = base.replacen(P2_CTOR_FROM, P2_CTOR_TO, 1).replacen(P2_LEADER_READ, OPT_ALLOWLIST, 1);
    const PRAGMA: &str = "pragma silverscript ^0.1.0;\n";
    let body = s.strip_prefix(PRAGMA).ok_or(Kcc20LimitError::Pattern("pragma silverscript ^0.1.0;"))?;
    Ok(format!("{PRAGMA}{OPT_HEADER}{body}"))
}

/// The `next_states` argument of a KCC-20 leader (`transfer`) signature script under the token program `tpl`, decoded
/// with the strict KCC-1 decoder ([`crate::kcc1::split_invocation`], [`crate::kcc1::decode_arguments`]): the
/// invocation layout, the dispatch tag of `transfer`, every push in its `PushMinimal` form, the `State[]` field groups
/// of equal length and every `int` amount in its eight-byte signed-magnitude form. `None` for anything else (another
/// entry, a malformed or non-canonical encoding).
pub fn transfer_next_states(tpl: &crate::artifacts::Template, signature_script: &[u8]) -> Option<Vec<crate::state::Kcc20State>> {
    use crate::state::FieldMap;
    use silverscript_abi::ArtifactValue;
    let (args, tag, _redeem) = crate::kcc1::split_invocation(signature_script).ok()?;
    let c = tpl.contract();
    let e = c.entry("transfer")?;
    if e.dispatch_tag.into_bytes() != tag {
        return None;
    }
    let types: Vec<_> = e.params.iter().map(|p| p.ty.clone()).collect();
    let values = crate::kcc1::decode_arguments(&types, &crate::kcc1::contract_records(&tpl.artifact, c), args).ok()?;
    let ArtifactValue::Array(states) = values.first()? else { return None };
    states
        .iter()
        .map(|s| match s {
            ArtifactValue::Object(m) => crate::state::Kcc20State::from_values(m).ok(),
            _ => None,
        })
        .collect()
}
