//! KOB protocol core.
//!
//! Single Rust implementation of everything that builds, encodes or checks a KOB
//! transaction. It is consumed natively (executor, CLI, tests) and, through `kob-wasm`,
//! by the web app and the x402 client SDK, so all clients share one code path.
//!
//! | Module | Contents |
//! |---|---|
//! | [`family`] | token families (KCC-20, KRON): what differs between them and nothing else |
//! | [`artifacts`] | embedded `silverc` artifacts and raw KRON token programs, template-hash pinning, network-constant checks |
//! | [`state`] | typed state of every order kind (both families) and the token states; the quote rule (`quote_of`) and the per-kind order arithmetic |
//! | [`kcc1`] / [`kcc2`] | KCC-1 hash notation, push forms, type names, dispatch tags, strict argument and state decoding; KCC-2 authority-scheme registry, authority values, minimum approval checks |
//! | [`script`] | signature-script encoding (entry args, dispatch tag, redeem push) |
//! | [`build`] | builders: create / cancel(-replace, stray sweep) / refund / kill / close / send; matcher batches (auctions, triggers, stop entries, repeat merges); keeper updates; two-token routes; pair orders (routed through the KAS books, netted against opposite pair orders, from inventory) |
//! | [`router`] | the KOB router (Argent): payment intents (KasToToken, TokenToKas, TokenSwap), their pinned actors and states |
//! | [`defaults`] | wallet defaults, day orders, per-program keeper tips derived from measured fees |
//! | [`tx`] | unsigned transaction + signing plan, fee/mass pass, wallet-signature finalisation |
//! | [`budget`] | compute-budget table (generated by the engine over every builder shape) |
//! | [`payload`] | `KOB1` versioned TLV payload and trustless order recovery |
//! | [`verify`] | validation through the rusty-kaspa v2.1.0 script engine (feature `engine`) |
//! | [`vectors`] | golden-vector file format |
//!
//! Flow: `build::build(&action)` -> [`tx::BuiltTx`] (unsigned tx, sign requests) -> wallet
//! signatures -> [`tx::finalize`] -> [`tx::SignedTx`] -> node RPC `submitTransaction`.

pub mod artifacts;
pub mod budget;
pub mod build;
pub mod defaults;
pub mod error;
pub mod family;
pub mod genesis_evidence;
pub mod issue;
pub mod json;
pub mod kcc1;
pub mod kcc2;
pub mod kcc20;
pub mod payload;
pub mod registry;
pub mod router;
pub mod script;
pub mod state;
pub mod tx;
pub mod vectors;
#[cfg(feature = "engine")]
pub mod verify;

pub use error::{Error, Result};
pub use family::Family;

/// Crate version, exposed so front ends can report which protocol build they run.
pub const VERSION: &str = env!("CARGO_PKG_VERSION");
