// Writes the deployment record of a network (called by scripts/build-deploy.sh from the repo root; see
// that script).
//
//   node scripts/lib/deploy.mjs <network> <out dir>
//
// No template depends on a network or a genesis (protocol v2.6: a stop is armed by a fill in the same
// transaction; there is no receipt covenant and no R_ID), so a deployment deploys the reference artifacts
// under contracts/artifacts unchanged. The record lists them (name, artifact, template hash, prefix /
// suffix lengths) so that a binary built for the network (cargo feature deploy-<network>) can check what it
// embeds. Writes <out dir>/deployment.json and <out dir>/DEPLOYMENT.md.
//
// When registry/tokens.json is the registry OF THIS NETWORK (its `network` field; today: mainnet), the record also
// pins it: path, sha256 of its bytes (line endings normalised to LF, as SHA256SUMS hashes them), its strict
// template list and its listed tokens. A deploy-mainnet binary embeds the same file and checks the pin, and the
// web build pins the same sha256 (web/registry-pin.mjs), so a changed registry makes the record stale.
import { createHash } from 'node:crypto';
import fs from 'node:fs';

const [network, out] = process.argv.slice(2);
const die = (m) => {
  console.error(`build-deploy: ${m}`);
  process.exit(1);
};
if (!/^[a-z0-9-]+$/.test(network || '')) die(`bad network ${network}`);
const readLf = (f) => fs.readFileSync(f, 'utf8').replace(/\r/g, '');
const toHex = (b) => Buffer.from(b).toString('hex');

// The KOB order kinds (the KOB1 kind codes 0x01..0x06 and 0x08..0x0a; 0x07, a retired receipt kind, is unused): the six
// plain, conditional and if-done kinds in both families, and the three pair templates that serve both (KobPair, KobCondPair, KobIfdPair).
const KINDS = ['KobAsk', 'KobBid', 'KobCondAsk', 'KobCondBid', 'KobIfdBid', 'KobIfdAsk'];
const names = [...KINDS, 'KobPair', 'KobCondPair', 'KobIfdPair', ...KINDS.map((k) => `${k}Kron`)];
const templates = names.map((name) => {
  const file = `contracts/artifacts/${name}.json`;
  if (!fs.existsSync(file)) die(`${file} is missing`);
  const c = JSON.parse(readLf(file)).contracts[name];
  if (!c) die(`${file} has no contract ${name}`);
  const { bytecode, template_hash, state_span } = c.compiled;
  return {
    name,
    artifact: file,
    hash: toHex(template_hash),
    prefix_len: state_span.offset,
    suffix_len: bytecode.length - state_span.offset - state_span.len,
  };
});
// The token registry of this network, when the repository ships one (registry/tokens.json is the mainnet registry).
const REGISTRY = 'registry/tokens.json';
let registry = null;
if (fs.existsSync(REGISTRY)) {
  const text = readLf(REGISTRY);
  const doc = JSON.parse(text);
  if (doc.network === network) {
    registry = {
      path: REGISTRY,
      sha256: createHash('sha256').update(text, 'utf8').digest('hex'),
      schema_version: doc.schema_version,
      strict_templates: doc.templates.filter((t) => t.review_status === 'reviewed').map((t) => ({ id: t.id, template_hash: t.template_hash })),
      pending_templates: doc.templates.filter((t) => t.review_status !== 'reviewed').map((t) => t.id),
      listed: doc.tokens
        .filter((t) => t.status === 'listed')
        .map((t) => ({ ticker: t.ticker, covenant_id: t.covenant_id, official: t.official === true })),
    };
  }
}
const manifest = {
  network,
  protocol: 'v3 (no lots: base units, prices per whole base token; pair orders A/B, one template per pair kind for both families)',
  compiler: `silverc ${readLf('contracts/silverc.lock').match(/^version (\S+)$/m)[1]} (contracts/silverc.lock)`,
  note: 'every template is the reference artifact under contracts/artifacts; nothing is substituted per network',
  templates,
  ...(registry ? { registry } : {}),
};
fs.mkdirSync(out, { recursive: true });
fs.writeFileSync(`${out}/deployment.json`, JSON.stringify(manifest, null, 2) + '\n');

const rows = templates.map((t) => `| ${t.name} | \`${t.hash}\` | ${t.prefix_len} / ${t.suffix_len} |`);
fs.writeFileSync(
  `${out}/DEPLOYMENT.md`,
  `# KOB deployment: ${network}

Generated by \`scripts/build-deploy.sh ${network}\` (do not edit; \`--check\` reproduces it).

| | |
|---|---|
| Network | ${network} |
| Protocol | ${manifest.protocol} |
| Compiler | ${manifest.compiler} |

Since protocol v2.6 a stop, stop-limit, trailing stop, OCO stop leg or stop entry is armed by the fill of a
plain resting order in the same transaction (touch trigger). There is no receipt covenant, no \`R_ID\` and no
genesis step: the templates below are the reference artifacts of \`contracts/artifacts\`, final at build time,
the same on every network.

| Template | Template hash | prefix / suffix |
|---|---|---|
${rows.join('\n')}

The token programs are the reference artifacts too. Binaries embedding this record: see "Deployment
builds" in contracts/README.md.
${registry ? registrySection(registry) : ''}`,
);

function registrySection(r) {
  const code = (s) => '`' + s + '`';
  const tokens = r.listed.map((t) => `| ${t.ticker} | ${code(t.covenant_id)} | ${t.official ? 'official' : 'listed, not official'} |`);
  return `
## Token registry (pinned)

| | |
|---|---|
| File | ${code(r.path)} (schema ${r.schema_version}) |
| sha256 (LF) | ${code(r.sha256)} |
| Strict templates | ${r.strict_templates.map((t) => `${t.id} ${code(t.template_hash)}`).join(', ') || 'none'} |
| Pending review | ${r.pending_templates.join(', ') || 'none'} |

The deploy-${network} build embeds this file as its default registry and checks this hash; the web build
pins the same hash (${code('web/registry-pin.mjs')}). An operator may load another registry (${code('--tokens')}):
its hash is reported by ${code('GET /v1/tokens')} and the web app shows it as a non-default registry.

| Listed token | Covenant id | Standing |
|---|---|---|
${tokens.join('\n')}
`;
}
for (const t of templates) console.log(`${t.name.padEnd(16)} ${t.hash}`);
