// Report writer: results.md (tables) and results.json.
import fs from 'node:fs';
import path from 'node:path';

const shortTpl = n => n.replace(/^kron_token_/, '').replace(/\.bin$/, '');
const cell = s => String(s ?? '').replace(/\|/g, '\\|').replace(/\n/g, ' ');

export function totals(suiteResults) {
  const t = { mutations: 0, confirmed: 0, held: 0, heldTotal: 0, failed: 0, editErrors: 0 };
  for (const s of suiteResults) {
    for (const m of s.mutations) {
      if (m.holdOnly) t.heldTotal++;
      else t.mutations++;
      if (m.status === 'CONFIRMED') t.confirmed++;
      else if (m.status === 'HELD') t.held++;
      else if (m.status === 'EDIT-ERROR') t.editErrors++;
      else t.failed++;
    }
  }
  return t;
}

export function totalsLine(t) {
  let s = `${t.confirmed}/${t.mutations} confirmed`;
  if (t.heldTotal) s += `, ${t.held}/${t.heldTotal} defence-in-depth held (expected NOT to flip)`;
  if (t.failed) s += `, ${t.failed} not confirmed`;
  if (t.editErrors) s += `, ${t.editErrors} edit errors`;
  return s;
}

function suiteTable(s) {
  const cols = s.templates.length ? s.templates : [''];
  let md = `| id | contract | check ablated | expected | ${cols.map(c => (c ? `flipped ${shortTpl(c)}` : 'flipped')).join(' | ')} | status |\n`;
  md += `|---|---|---|---|${cols.map(() => '---|').join('')}---|\n`;
  for (const m of s.mutations) {
    const exp = [m.expect.length ? m.expect.join(', ') : '', m.hold?.length ? `stay rejected: ${m.hold.join(', ')}` : ''].filter(Boolean).join('; ');
    const flips = cols.map(c => cell((m.flipped?.[c] ?? []).join(' ')));
    let status = m.status;
    if (m.status === 'HELD') status = 'held (defence in depth)';
    if (m.status === 'EDIT-ERROR' || m.status === 'NOT-CONFIRMED' || m.status === 'BASELINE-DIRTY') status += ': ' + m.why.join('; ');
    else if (m.notes?.length) status += ' (' + m.notes.join('; ') + ')';
    if (m.posFails?.length) status += ` [positive scenarios rejected: ${m.posFails.join(' ')}]`;
    md += `| ${cell(m.id)} | ${cell(m.file)} | ${cell(m.note)} | ${cell(exp)} | ${flips.join(' | ')} | ${cell(status)} |\n`;
  }
  return md;
}

export function writeReport(outDir, meta, suiteResults) {
  const t = totals(suiteResults);
  let md = `# Ablation results\n\nGenerated by \`tools/ablation/ablate.mjs\` on ${meta.date}. Total: **${totalsLine(t)}**.\n`;
  md += `Wall time ${meta.secs}s, ${meta.jobs} parallel jobs.\n`;
  for (const s of suiteResults) {
    const st = totals([s]);
    md += `\n## ${s.name}\n\n${s.family}; test binary \`${s.testBin}\`; contracts \`${s.srcDir}\`. ${totalsLine(st)}.\n`;
    if (s.baseline.length) {
      md += `Baseline (no mutation): ${s.baseline.map(b => `${b.testFn} ${b.ok ? 'clean' : 'DIRTY (' + b.why.join('; ') + ')'}`).join(', ')}.\n`;
    }
    md += '\n' + suiteTable(s);
    const coll = s.mutations.filter(m => m.collateral?.length);
    if (coll.length) {
      md += `\nCollateral flips (scenarios accepted besides the expected ones):\n\n`;
      for (const m of coll) md += `- ${m.id}: ${m.collateral.join(' ')}\n`;
    }
  }
  fs.mkdirSync(outDir, { recursive: true });
  fs.writeFileSync(path.join(outDir, 'results.md'), md);
  const json = { ...meta, totals: t, suites: suiteResults };
  fs.writeFileSync(path.join(outDir, 'results.json'), JSON.stringify(json, null, 1) + '\n');
  return t;
}
